import { Hono } from 'hono';
import { all, first, run } from '../lib/db.js';
import { ok, fail, jsonBody } from '../lib/http.js';
import { requirePermission } from '../lib/auth.js';
import { audit } from '../lib/audit.js';
import { normalizeText, nextCode, normalizeSerial } from '../lib/codes.js';

export const adminRoutes = new Hono();
const MODULES=['DASHBOARD','PROCUREMENT','SHIPMENTS','RECEIVING','INVENTORY','RETURNS','REQUISITIONS','DELIVERIES','SALES','CUSTOMERS','STATIONS','PLANNING','ADMIN'];

adminRoutes.get('/users', requirePermission('ADMIN','MANAGE'), async c=>{const users=await all(c.env.DB,`SELECT * FROM erp_users ORDER BY active DESC,email`);const roles=await all(c.env.DB,`SELECT * FROM erp_roles ORDER BY name`);const permissions=await all(c.env.DB,`SELECT * FROM erp_role_permissions ORDER BY role_code,module`);return ok(c,{users,roles,permissions,modules:MODULES});});

adminRoutes.post('/users', requirePermission('ADMIN','MANAGE'), async c=>{const b=await jsonBody(c);const email=normalizeText(b.email).toLowerCase();if(!email.endsWith('@nrdev.ph'))return fail(c,'Only @nrdev.ph accounts are allowed');const before=await first(c.env.DB,`SELECT * FROM erp_users WHERE email=?`,[email]);if(before){await run(c.env.DB,`UPDATE erp_users SET display_name=?,role_code=?,department=?,live_access=?,active=? WHERE email=?`,[normalizeText(b.displayName||before.display_name),b.roleCode||before.role_code,normalizeText(b.department),b.liveAccess?1:0,b.active===false?0:1,email]);}else{await run(c.env.DB,`INSERT INTO erp_users(email,display_name,role_code,department,live_access,active) VALUES(?,?,?,?,?,?)`,[email,normalizeText(b.displayName||email.split('@')[0]),b.roleCode||'STAFF',normalizeText(b.department),b.liveAccess?1:0,b.active===false?0:1]);}const after=await first(c.env.DB,`SELECT * FROM erp_users WHERE email=?`,[email]);await audit(c,{action:before?'UPDATE_USER':'CREATE_USER',module:'ADMIN',recordType:'USER',recordId:after.id,recordNo:email,before,after});return ok(c,{user:after});});

adminRoutes.post('/permissions/:role', requirePermission('ADMIN','MANAGE'), async c=>{const role=normalizeText(c.req.param('role')).toUpperCase();const b=await jsonBody(c);const rows=Array.isArray(b.permissions)?b.permissions:[];for(const p of rows){if(!MODULES.includes(p.module))continue;await run(c.env.DB,`INSERT INTO erp_role_permissions(role_code,module,can_view,can_create,can_edit,can_approve,can_post,can_export,can_manage) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(role_code,module) DO UPDATE SET can_view=excluded.can_view,can_create=excluded.can_create,can_edit=excluded.can_edit,can_approve=excluded.can_approve,can_post=excluded.can_post,can_export=excluded.can_export,can_manage=excluded.can_manage`,[role,p.module,p.canView?1:0,p.canCreate?1:0,p.canEdit?1:0,p.canApprove?1:0,p.canPost?1:0,p.canExport?1:0,p.canManage?1:0]);}await audit(c,{action:'UPDATE_PERMISSIONS',module:'ADMIN',recordType:'ROLE',recordNo:role,after:{permissions:rows}});return ok(c,{updated:rows.length});});

adminRoutes.get('/diagnostics', requirePermission('ADMIN','MANAGE'), async c=>{const tables=['erp_items','erp_partners','erp_shipments','erp_expected_assets','erp_receipts','erp_assets','erp_stock_ledger','erp_requisitions','erp_sales_orders','erp_deliveries','erp_reconciliation_cases','erp_serial_exceptions'];const counts={};for(const table of tables){counts[table]=(await first(c.env.DB,`SELECT COUNT(*) n FROM ${table}`))?.n||0;}const invariants={duplicateAssets:(await first(c.env.DB,`SELECT COUNT(*) n FROM (SELECT serial_no FROM erp_assets GROUP BY serial_no HAVING COUNT(*)>1)`))?.n||0,orphanMovements:(await first(c.env.DB,`SELECT COUNT(*) n FROM erp_stock_ledger l LEFT JOIN erp_assets a ON a.id=l.asset_id WHERE l.asset_id IS NOT NULL AND a.id IS NULL`))?.n||0,unreconciled:(await first(c.env.DB,`SELECT COUNT(*) n FROM erp_reconciliation_cases WHERE status='UNRECONCILED'`))?.n||0,availableOnHold:(await first(c.env.DB,`SELECT COUNT(*) n FROM erp_assets WHERE current_status IN ('AVAILABLE','IN_STOCK') AND reconciliation_status!='CLEAR'`))?.n||0};return ok(c,{counts,invariants,healthy:invariants.duplicateAssets===0&&invariants.orphanMovements===0});});

adminRoutes.post('/qr-review', requirePermission('INVENTORY','CREATE'), async c=>{const b=await jsonBody(c);const serial=normalizeSerial(b.detectedSerial||b.rawPayload);const asset=serial?await first(c.env.DB,`SELECT * FROM erp_assets WHERE serial_no=? OR secondary_serial=? LIMIT 1`,[serial,serial]):null;const no=await nextCode(c.env.DB,'QR_REVIEW','QR',8);const r=await run(c.env.DB,`INSERT INTO erp_qr_reviews(review_no,module,raw_payload,detected_serial,asset_id,status,created_by) VALUES(?,?,?,?,?,'FOR_REVIEW',?)`,[no,b.module||'INVENTORY',normalizeText(b.rawPayload),serial,asset?.id||null,c.get('erpUser').email]);return ok(c,{id:r.meta.last_row_id,reviewNo:no,detectedSerial:serial,asset,found:!!asset},201);});

adminRoutes.post('/qr-review/:id/confirm', requirePermission('INVENTORY','POST'), async c=>{const id=Number(c.req.param('id'));const b=await jsonBody(c);const before=await first(c.env.DB,`SELECT * FROM erp_qr_reviews WHERE id=?`,[id]);if(!before)return fail(c,'QR review not found',404);await run(c.env.DB,`UPDATE erp_qr_reviews SET status='CONFIRMED',detected_serial=COALESCE(?,detected_serial),reviewed_by=?,reviewed_at=datetime('now'),posted_record_type=?,posted_record_id=? WHERE id=?`,[b.detectedSerial||null,c.get('erpUser').email,b.postedRecordType||'',b.postedRecordId||null,id]);return ok(c,{confirmed:true});});
