import { Hono } from 'hono';
import { all, first, run } from '../lib/db.js';
import { ok, fail, jsonBody, pageParams } from '../lib/http.js';
import { requirePermission } from '../lib/auth.js';
import { audit } from '../lib/audit.js';
import { postMovement } from '../lib/inventory.js';
import { nextCode, normalizeText } from '../lib/codes.js';

export const deliveryRoutes = new Hono();

deliveryRoutes.get('/', requirePermission('DELIVERIES','VIEW'), async c => {
  const {page,size,offset}=pageParams(c);const q=`%${normalizeText(c.req.query('q'))}%`;const status=normalizeText(c.req.query('status'));const where=[];const args=[];if(q!=='%%'){where.push('(d.delivery_no LIKE ? OR d.destination LIKE ? OR d.recipient_name LIKE ?)');args.push(q,q,q);}if(status){where.push('d.status=?');args.push(status);}const w=where.length?`WHERE ${where.join(' AND ')}`:'';
  const rows=await all(c.env.DB,`SELECT d.*,s.sales_order_no,r.requisition_no,a.assignment_no,(SELECT COUNT(*) FROM erp_delivery_assets da WHERE da.delivery_id=d.id) asset_count FROM erp_deliveries d LEFT JOIN erp_sales_orders s ON s.id=d.sales_order_id LEFT JOIN erp_requisitions r ON r.id=d.requisition_id LEFT JOIN erp_assignments a ON a.id=d.assignment_id ${w} ORDER BY COALESCE(d.scheduled_date,d.requested_date,d.created_at) DESC LIMIT ? OFFSET ?`,[...args,size,offset]);const total=await first(c.env.DB,`SELECT COUNT(*) n FROM erp_deliveries d ${w}`,args);return ok(c,{rows,page,size,total:total?.n||0});
});

deliveryRoutes.post('/', requirePermission('DELIVERIES','CREATE'), async c => {
  const b=await jsonBody(c);const no=normalizeText(b.deliveryNo)||await nextCode(c.env.DB,'DELIVERY','DLV',6);const r=await run(c.env.DB,`INSERT INTO erp_deliveries(delivery_no,assignment_id,sales_order_id,requisition_id,requested_date,scheduled_date,origin_location_id,destination,recipient_name,recipient_phone,status,source_system,source_key,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,'PLANNED',?,?,?)`,[no,b.assignmentId||null,b.salesOrderId||null,b.requisitionId||null,b.requestedDate||new Date().toISOString().slice(0,10),b.scheduledDate||'',b.originLocationId||null,normalizeText(b.destination),normalizeText(b.recipientName),normalizeText(b.recipientPhone),normalizeText(b.sourceSystem||'E88_FINSYS'),normalizeText(b.sourceKey),c.get('erpUser').email]);for(const asset of (b.assets||[])){await run(c.env.DB,`INSERT OR IGNORE INTO erp_delivery_assets(delivery_id,asset_id,serial_no,item_code,qty) SELECT ?,id,serial_no,item_code,1 FROM erp_assets WHERE serial_no=?`,[r.meta.last_row_id,normalizeText(asset.serialNo||asset)]);}await audit(c,{action:'CREATE',module:'DELIVERIES',recordType:'DELIVERY',recordId:r.meta.last_row_id,recordNo:no,after:b});return ok(c,{id:r.meta.last_row_id,deliveryNo:no},201);
});

deliveryRoutes.get('/:id', requirePermission('DELIVERIES','VIEW'), async c => {
  const id=Number(c.req.param('id'));const header=await first(c.env.DB,`SELECT d.*,s.sales_order_no,s.transaction_type,r.requisition_no,a.assignment_no,l.code origin_location_code,l.name origin_location_name FROM erp_deliveries d LEFT JOIN erp_sales_orders s ON s.id=d.sales_order_id LEFT JOIN erp_requisitions r ON r.id=d.requisition_id LEFT JOIN erp_assignments a ON a.id=d.assignment_id LEFT JOIN erp_locations l ON l.id=d.origin_location_id WHERE d.id=?`,[id]);if(!header)return fail(c,'Delivery not found',404);const assets=await all(c.env.DB,`SELECT da.*,a.category,a.item_name,a.current_status,a.current_location_code,a.reconciliation_status FROM erp_delivery_assets da LEFT JOIN erp_assets a ON a.id=da.asset_id WHERE da.delivery_id=? ORDER BY da.id`,[id]);const checks=await all(c.env.DB,`SELECT * FROM erp_pre_release_checks WHERE serial_no IN (SELECT serial_no FROM erp_delivery_assets WHERE delivery_id=?) ORDER BY check_date DESC`,[id]);return ok(c,{header,assets,checks});
});

deliveryRoutes.post('/:id/release', requirePermission('DELIVERIES','POST'), async c => {
  const id=Number(c.req.param('id'));const b=await jsonBody(c);const header=await first(c.env.DB,`SELECT d.*,s.transaction_type,s.customer_id,p.name customer_name FROM erp_deliveries d LEFT JOIN erp_sales_orders s ON s.id=d.sales_order_id LEFT JOIN erp_partners p ON p.id=s.customer_id WHERE d.id=?`,[id]);if(!header)return fail(c,'Delivery not found',404);if(!['PLANNED','READY'].includes(header.status))return fail(c,'Delivery is not ready for release',409);const assets=await all(c.env.DB,`SELECT da.*,a.* FROM erp_delivery_assets da JOIN erp_assets a ON a.id=da.asset_id WHERE da.delivery_id=?`,[id]);if(!assets.length)return fail(c,'No assets are attached to this delivery');
  for(const asset of assets){if(asset.reconciliation_status!=='CLEAR')return fail(c,`Serial ${asset.serial_no} has an unresolved reconciliation case`,409);const check=await first(c.env.DB,`SELECT * FROM erp_pre_release_checks WHERE serial_no=? ORDER BY id DESC LIMIT 1`,[asset.serial_no]);if(asset.category==='MC'&&check&&check.result==='FAILED')return fail(c,`Serial ${asset.serial_no} failed pre-release inspection`,409);try{await postMovement(c.env.DB,{serialNo:asset.serial_no,movementType:'OUTBOUND_RELEASE',movementDate:b.releaseDate||new Date().toISOString(),toLocationId:null,toLocationCode:normalizeText(header.destination),toStatus:'OUT_FOR_DELIVERY',holderType:'CUSTOMER',holderId:header.customer_id||null,holderName:header.customer_name||header.recipient_name,sourceDocType:'DELIVERY',sourceDocId:id,sourceDocNo:header.delivery_no,reasonCode:header.transaction_type||'DELIVERY',notes:normalizeText(b.notes)},c.get('erpUser').email);}catch(e){return fail(c,e.message,409);}}
  await run(c.env.DB,`UPDATE erp_deliveries SET status='RELEASED',actual_release_date=? WHERE id=?`,[b.releaseDate||new Date().toISOString(),id]);await audit(c,{action:'RELEASE',module:'DELIVERIES',recordType:'DELIVERY',recordId:id,recordNo:header.delivery_no,after:{assets:assets.map(x=>x.serial_no)}});return ok(c,{released:assets.length});
});

deliveryRoutes.post('/:id/complete', requirePermission('DELIVERIES','POST'), async c => {
  const id=Number(c.req.param('id'));const b=await jsonBody(c);const header=await first(c.env.DB,`SELECT d.*,s.transaction_type,s.customer_id,p.name customer_name FROM erp_deliveries d LEFT JOIN erp_sales_orders s ON s.id=d.sales_order_id LEFT JOIN erp_partners p ON p.id=s.customer_id WHERE d.id=?`,[id]);if(!header)return fail(c,'Delivery not found',404);if(header.status!=='RELEASED')return fail(c,'Only released deliveries can be completed',409);const assets=await all(c.env.DB,`SELECT da.*,a.category FROM erp_delivery_assets da LEFT JOIN erp_assets a ON a.id=da.asset_id WHERE da.delivery_id=?`,[id]);const target=header.transaction_type==='SALE'?'SOLD':header.transaction_type==='DEMO'?'DEMO':header.transaction_type==='PILOT'?'PILOT_TEST':'LEASED';for(const asset of assets.filter(x=>x.serial_no)){try{await postMovement(c.env.DB,{serialNo:asset.serial_no,movementType:'DELIVERED',movementDate:b.deliveryDate||new Date().toISOString(),toLocationId:null,toLocationCode:normalizeText(header.destination),toStatus:target,holderType:'CUSTOMER',holderId:header.customer_id||null,holderName:header.customer_name||header.recipient_name,sourceDocType:'DELIVERY',sourceDocId:id,sourceDocNo:header.delivery_no,reasonCode:header.transaction_type||'DELIVERY',notes:normalizeText(b.notes)},c.get('erpUser').email);}catch(e){return fail(c,e.message,409);}}
  await run(c.env.DB,`UPDATE erp_deliveries SET status='DELIVERED',actual_delivery_date=?,proof_document_url=COALESCE(?,proof_document_url) WHERE id=?`,[b.deliveryDate||new Date().toISOString(),b.proofDocumentUrl||null,id]);if(header.sales_order_id)await run(c.env.DB,`UPDATE erp_sales_orders SET status='POSTED',posted_by=?,posted_at=datetime('now') WHERE id=?`,[c.get('erpUser').email,header.sales_order_id]);if(header.assignment_id)await run(c.env.DB,`UPDATE erp_assignments SET status='ACTIVE' WHERE id=?`,[header.assignment_id]);await audit(c,{action:'COMPLETE',module:'DELIVERIES',recordType:'DELIVERY',recordId:id,recordNo:header.delivery_no,after:{status:'DELIVERED',target}});return ok(c,{delivered:assets.length,status:target});
});
