import { Hono } from 'hono';
import { all, first, run } from '../lib/db.js';
import { ok, fail, jsonBody, pageParams, numberValue } from '../lib/http.js';
import { requirePermission } from '../lib/auth.js';
import { audit } from '../lib/audit.js';
import { ensurePartner, nextCode, normalizeText, normalizeSerial } from '../lib/codes.js';
import { getAsset, isAvailable, postMovement } from '../lib/inventory.js';

export const stationRoutes = new Hono();

stationRoutes.get('/', requirePermission('STATIONS','VIEW'), async c=>{const {page,size,offset}=pageParams(c);const rows=await all(c.env.DB,`SELECT p.*,x.name partner_name,(SELECT COUNT(*) FROM erp_station_project_assets a WHERE a.project_id=p.id) asset_count FROM erp_station_projects p LEFT JOIN erp_partners x ON x.id=p.partner_id ORDER BY COALESCE(p.target_activation_date,p.planned_date,p.created_at) DESC LIMIT ? OFFSET ?`,[size,offset]);const total=await first(c.env.DB,`SELECT COUNT(*) n FROM erp_station_projects`);return ok(c,{rows,page,size,total:total?.n||0});});

stationRoutes.post('/', requirePermission('STATIONS','CREATE'), async c=>{const b=await jsonBody(c);if(!b.siteName)return fail(c,'Site name is required');let partner=null;if(b.partnerName)partner=await ensurePartner(c.env.DB,{name:b.partnerName,type:'SITE_PARTNER',address:b.plannedLocation||'',sourceSystem:b.sourceSystem||'E88_FINSYS'});const no=normalizeText(b.projectNo)||await nextCode(c.env.DB,'STATION_PROJECT','BSSP',6);const r=await run(c.env.DB,`INSERT INTO erp_station_projects(project_no,site_name,partner_id,planned_location,planned_date,target_activation_date,actual_activation_date,progress_pct,status,budget_amount,actual_cost) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,[no,b.siteName,partner?.id||null,b.plannedLocation||'',b.plannedDate||'',b.targetActivationDate||'',b.actualActivationDate||'',numberValue(b.progressPct),b.status||'PLANNED',numberValue(b.budgetAmount),numberValue(b.actualCost)]);await audit(c,{action:'CREATE',module:'STATIONS',recordType:'STATION_PROJECT',recordId:r.meta.last_row_id,recordNo:no,after:b});return ok(c,{id:r.meta.last_row_id,projectNo:no},201);});

stationRoutes.get('/:id', requirePermission('STATIONS','VIEW'), async c=>{const id=Number(c.req.param('id'));const header=await first(c.env.DB,`SELECT p.*,x.name partner_name FROM erp_station_projects p LEFT JOIN erp_partners x ON x.id=p.partner_id WHERE p.id=?`,[id]);if(!header)return fail(c,'Station project not found',404);const assets=await all(c.env.DB,`SELECT pa.*,a.category,a.item_name,a.current_status,a.current_location_code,a.reconciliation_status FROM erp_station_project_assets pa LEFT JOIN erp_assets a ON a.id=pa.asset_id WHERE pa.project_id=?`,[id]);return ok(c,{header,assets});});

stationRoutes.post('/:id/update', requirePermission('STATIONS','EDIT'), async c=>{const id=Number(c.req.param('id'));const b=await jsonBody(c);const before=await first(c.env.DB,`SELECT * FROM erp_station_projects WHERE id=?`,[id]);if(!before)return fail(c,'Station project not found',404);await run(c.env.DB,`UPDATE erp_station_projects SET planned_location=COALESCE(?,planned_location),planned_date=COALESCE(?,planned_date),target_activation_date=COALESCE(?,target_activation_date),actual_activation_date=COALESCE(?,actual_activation_date),progress_pct=COALESCE(?,progress_pct),status=COALESCE(?,status),budget_amount=COALESCE(?,budget_amount),actual_cost=COALESCE(?,actual_cost) WHERE id=?`,[b.plannedLocation??null,b.plannedDate??null,b.targetActivationDate??null,b.actualActivationDate??null,b.progressPct??null,b.status??null,b.budgetAmount??null,b.actualCost??null,id]);const after=await first(c.env.DB,`SELECT * FROM erp_station_projects WHERE id=?`,[id]);await audit(c,{action:'UPDATE',module:'STATIONS',recordType:'STATION_PROJECT',recordId:id,recordNo:after.project_no,before,after});return ok(c,{project:after});});

stationRoutes.post('/:id/assets', requirePermission('STATIONS','POST'), async c=>{const id=Number(c.req.param('id'));const b=await jsonBody(c);const project=await first(c.env.DB,`SELECT * FROM erp_station_projects WHERE id=?`,[id]);if(!project)return fail(c,'Station project not found',404);const asset=await getAsset(c.env.DB,normalizeSerial(b.serialNo));if(!asset)return fail(c,'Serial is not registered',404);if(!isAvailable(asset))return fail(c,`Serial ${asset.serial_no} is not available`,409);await run(c.env.DB,`INSERT OR IGNORE INTO erp_station_project_assets(project_id,asset_id,serial_no,asset_role,assigned_date,status) VALUES(?,?,?,?,?,'ASSIGNED')`,[id,asset.id,asset.serial_no,b.assetRole||asset.category,b.assignedDate||new Date().toISOString()]);try{await postMovement(c.env.DB,{serialNo:asset.serial_no,movementType:'STATION_DEPLOYMENT',movementDate:b.assignedDate||new Date().toISOString(),toLocationCode:project.planned_location,toStatus:'ASSIGNED_TO_STATION',holderType:'STATION_PROJECT',holderId:id,holderName:project.site_name,sourceDocType:'STATION_PROJECT',sourceDocId:id,sourceDocNo:project.project_no,reasonCode:b.assetRole||asset.category},c.get('erpUser').email);}catch(e){return fail(c,e.message,409);}await audit(c,{action:'ASSIGN_ASSET',module:'STATIONS',recordType:'STATION_PROJECT',recordId:id,recordNo:project.project_no,after:{serialNo:asset.serial_no,assetRole:b.assetRole}});return ok(c,{assigned:true});});

stationRoutes.post('/:id/activate', requirePermission('STATIONS','APPROVE'), async c=>{const id=Number(c.req.param('id'));const project=await first(c.env.DB,`SELECT * FROM erp_station_projects WHERE id=?`,[id]);if(!project)return fail(c,'Station project not found',404);const counts=await all(c.env.DB,`SELECT a.category,COUNT(*) qty FROM erp_station_project_assets pa JOIN erp_assets a ON a.id=pa.asset_id WHERE pa.project_id=? GROUP BY a.category`,[id]);const map=Object.fromEntries(counts.map(x=>[x.category,x.qty]));if(!(map.BSS>0))return fail(c,'A swapping-station/locker serial must be assigned before activation',409);if(!(map.BAT>0))return fail(c,'At least one battery must be assigned before activation',409);await run(c.env.DB,`UPDATE erp_station_projects SET status='ACTIVE',progress_pct=100,actual_activation_date=COALESCE(actual_activation_date,?) WHERE id=?`,[new Date().toISOString().slice(0,10),id]);await audit(c,{action:'ACTIVATE',module:'STATIONS',recordType:'STATION_PROJECT',recordId:id,recordNo:project.project_no,after:{status:'ACTIVE',counts:map}});return ok(c,{active:true,counts:map});});
