-- E88 Enterprise System v13.0
-- Specialist operational engines for the wider Ramco/NetSuite-style enterprise scope.
-- These tables are linked to the existing workspace records while preserving specialist
-- line-level data, workflow dependencies, approvals, finance events and audit history.

CREATE TABLE IF NOT EXISTS erp_specialist_module_config (
  module_code TEXT PRIMARY KEY,
  domain_code TEXT NOT NULL,
  engine_code TEXT NOT NULL,
  line_engine_code TEXT,
  finance_event_type TEXT,
  requires_lines INTEGER NOT NULL DEFAULT 0,
  approval_required INTEGER NOT NULL DEFAULT 1,
  rollout_level TEXT NOT NULL DEFAULT 'SPECIALIST',
  active INTEGER NOT NULL DEFAULT 1,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS erp_approval_matrices (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  matrix_code TEXT NOT NULL UNIQUE,
  module_code TEXT NOT NULL,
  document_type TEXT NOT NULL DEFAULT '*',
  department TEXT NOT NULL DEFAULT '*',
  amount_from REAL NOT NULL DEFAULT 0,
  amount_to REAL,
  step_no INTEGER NOT NULL DEFAULT 1,
  approver_role_code TEXT NOT NULL,
  approver_user_id INTEGER REFERENCES erp_users(id),
  action_code TEXT NOT NULL DEFAULT 'APPROVE',
  active INTEGER NOT NULL DEFAULT 1,
  created_by TEXT NOT NULL DEFAULT 'system',
  created_at TEXT DEFAULT (datetime('now')),
  UNIQUE(module_code,document_type,department,amount_from,step_no)
);

CREATE TABLE IF NOT EXISTS erp_workflow_approvals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  module_code TEXT NOT NULL,
  record_id INTEGER NOT NULL REFERENCES erp_module_records(id),
  record_no TEXT NOT NULL,
  matrix_id INTEGER NOT NULL REFERENCES erp_approval_matrices(id),
  cycle_no INTEGER NOT NULL DEFAULT 1,
  step_no INTEGER NOT NULL,
  required_role_code TEXT NOT NULL,
  assigned_user_id INTEGER REFERENCES erp_users(id),
  action_code TEXT NOT NULL DEFAULT 'APPROVE',
  status TEXT NOT NULL DEFAULT 'PENDING',
  requested_by TEXT NOT NULL,
  requested_at TEXT DEFAULT (datetime('now')),
  decided_by TEXT,
  decided_at TEXT,
  decision_notes TEXT,
  UNIQUE(record_id,matrix_id,cycle_no,step_no)
);
CREATE INDEX IF NOT EXISTS idx_erp_workflow_approvals_queue
  ON erp_workflow_approvals(status,required_role_code,module_code,requested_at);

CREATE TABLE IF NOT EXISTS erp_core_workflow_approvals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source_module TEXT NOT NULL,
  source_type TEXT NOT NULL,
  source_id INTEGER NOT NULL,
  source_no TEXT NOT NULL,
  matrix_id INTEGER NOT NULL REFERENCES erp_approval_matrices(id),
  cycle_no INTEGER NOT NULL DEFAULT 1,
  step_no INTEGER NOT NULL,
  required_role_code TEXT NOT NULL,
  assigned_user_id INTEGER REFERENCES erp_users(id),
  status TEXT NOT NULL DEFAULT 'PENDING',
  requested_by TEXT NOT NULL,
  requested_at TEXT DEFAULT (datetime('now')),
  decided_by TEXT,
  decided_at TEXT,
  decision_notes TEXT,
  UNIQUE(source_module,source_type,source_id,matrix_id,cycle_no,step_no)
);
CREATE INDEX IF NOT EXISTS idx_erp_core_workflow_approval_queue
  ON erp_core_workflow_approvals(status,required_role_code,source_module,requested_at);

CREATE TABLE IF NOT EXISTS erp_enterprise_record_links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source_module_code TEXT NOT NULL,
  source_record_id INTEGER NOT NULL REFERENCES erp_module_records(id),
  source_record_no TEXT NOT NULL,
  target_module_code TEXT NOT NULL,
  target_record_id INTEGER NOT NULL REFERENCES erp_module_records(id),
  target_record_no TEXT NOT NULL,
  link_type TEXT NOT NULL,
  shared_reference TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_by TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now')),
  UNIQUE(source_module_code,source_record_id,target_module_code,target_record_id,link_type)
);
CREATE INDEX IF NOT EXISTS idx_erp_enterprise_links_source
  ON erp_enterprise_record_links(source_module_code,source_record_id,status);
CREATE INDEX IF NOT EXISTS idx_erp_enterprise_links_target
  ON erp_enterprise_record_links(target_module_code,target_record_id,status);

CREATE TABLE IF NOT EXISTS erp_crm_pipeline_records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_record_id INTEGER NOT NULL UNIQUE REFERENCES erp_module_records(id),
  record_no TEXT NOT NULL UNIQUE,
  record_type TEXT NOT NULL,
  customer_id INTEGER REFERENCES erp_partners(id),
  customer_name TEXT,
  contact_person TEXT,
  contact_email TEXT,
  mobile_no TEXT,
  lead_source TEXT,
  sales_stage TEXT,
  probability_pct REAL NOT NULL DEFAULT 0,
  expected_value REAL NOT NULL DEFAULT 0,
  expected_close_date TEXT,
  next_action TEXT,
  next_action_date TEXT,
  owner_email TEXT,
  status TEXT NOT NULL,
  created_by TEXT NOT NULL,
  updated_by TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_erp_crm_pipeline_stage ON erp_crm_pipeline_records(sales_stage,status,next_action_date);

CREATE TABLE IF NOT EXISTS erp_manufacturing_documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_record_id INTEGER NOT NULL UNIQUE REFERENCES erp_module_records(id),
  module_code TEXT NOT NULL,
  document_no TEXT NOT NULL UNIQUE,
  document_type TEXT NOT NULL,
  product_code TEXT,
  bom_version TEXT,
  work_order_no TEXT,
  work_center TEXT,
  resource_code TEXT,
  planned_qty REAL NOT NULL DEFAULT 0,
  good_qty REAL NOT NULL DEFAULT 0,
  reject_qty REAL NOT NULL DEFAULT 0,
  planned_start TEXT,
  planned_end TEXT,
  actual_start TEXT,
  actual_end TEXT,
  material_cost REAL NOT NULL DEFAULT 0,
  labor_hours REAL NOT NULL DEFAULT 0,
  labor_cost REAL NOT NULL DEFAULT 0,
  overhead_cost REAL NOT NULL DEFAULT 0,
  total_cost REAL NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  finance_event_id INTEGER REFERENCES erp_finance_source_events(id),
  created_by TEXT NOT NULL,
  updated_by TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_erp_mfg_work_order ON erp_manufacturing_documents(work_order_no,status);

CREATE TABLE IF NOT EXISTS erp_manufacturing_lines (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  document_id INTEGER NOT NULL REFERENCES erp_manufacturing_documents(id) ON DELETE RESTRICT,
  line_no INTEGER NOT NULL,
  line_type TEXT NOT NULL DEFAULT 'MATERIAL',
  item_id INTEGER REFERENCES erp_items(id),
  item_code TEXT,
  description TEXT,
  operation_no TEXT,
  resource_code TEXT,
  qty_planned REAL NOT NULL DEFAULT 0,
  qty_actual REAL NOT NULL DEFAULT 0,
  uom TEXT NOT NULL DEFAULT 'EA',
  hours REAL NOT NULL DEFAULT 0,
  unit_cost REAL NOT NULL DEFAULT 0,
  amount REAL NOT NULL DEFAULT 0,
  source_location_code TEXT,
  destination_location_code TEXT,
  status TEXT NOT NULL DEFAULT 'PLANNED',
  created_by TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now')),
  UNIQUE(document_id,line_no)
);

CREATE TABLE IF NOT EXISTS erp_quality_documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_record_id INTEGER NOT NULL UNIQUE REFERENCES erp_module_records(id),
  module_code TEXT NOT NULL,
  document_no TEXT NOT NULL UNIQUE,
  document_type TEXT NOT NULL,
  plan_code TEXT,
  inspection_no TEXT,
  item_code TEXT,
  serial_no TEXT,
  lot_no TEXT,
  supplier_name TEXT,
  inspection_stage TEXT,
  sample_qty REAL NOT NULL DEFAULT 0,
  accepted_qty REAL NOT NULL DEFAULT 0,
  rejected_qty REAL NOT NULL DEFAULT 0,
  disposition TEXT,
  risk_level TEXT,
  quality_score REAL NOT NULL DEFAULT 0,
  inspection_date TEXT,
  status TEXT NOT NULL,
  created_by TEXT NOT NULL,
  updated_by TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS erp_quality_results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  quality_document_id INTEGER NOT NULL REFERENCES erp_quality_documents(id) ON DELETE RESTRICT,
  line_no INTEGER NOT NULL,
  characteristic TEXT NOT NULL,
  test_method TEXT,
  lower_limit REAL,
  upper_limit REAL,
  measured_value TEXT,
  result_code TEXT NOT NULL DEFAULT 'PENDING',
  defect_code TEXT,
  corrective_action TEXT,
  inspector TEXT,
  inspected_at TEXT,
  created_by TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now')),
  UNIQUE(quality_document_id,line_no)
);

CREATE TABLE IF NOT EXISTS erp_project_documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_record_id INTEGER NOT NULL UNIQUE REFERENCES erp_module_records(id),
  module_code TEXT NOT NULL,
  document_no TEXT NOT NULL UNIQUE,
  document_type TEXT NOT NULL,
  project_code TEXT,
  project_name TEXT,
  customer_name TEXT,
  project_manager TEXT,
  sponsor TEXT,
  site_location TEXT,
  start_date TEXT,
  end_date TEXT,
  percent_complete REAL NOT NULL DEFAULT 0,
  original_budget REAL NOT NULL DEFAULT 0,
  revised_budget REAL NOT NULL DEFAULT 0,
  committed_cost REAL NOT NULL DEFAULT 0,
  actual_cost REAL NOT NULL DEFAULT 0,
  contract_value REAL NOT NULL DEFAULT 0,
  billed_amount REAL NOT NULL DEFAULT 0,
  recognized_revenue REAL NOT NULL DEFAULT 0,
  open_items INTEGER NOT NULL DEFAULT 0,
  health TEXT,
  status TEXT NOT NULL,
  finance_event_id INTEGER REFERENCES erp_finance_source_events(id),
  created_by TEXT NOT NULL,
  updated_by TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_erp_project_code ON erp_project_documents(project_code,status);
CREATE TABLE IF NOT EXISTS erp_project_lines (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_document_id INTEGER NOT NULL REFERENCES erp_project_documents(id) ON DELETE RESTRICT,
  line_no INTEGER NOT NULL,
  line_type TEXT NOT NULL DEFAULT 'TASK',
  reference_code TEXT,
  description TEXT NOT NULL,
  owner_email TEXT,
  start_date TEXT,
  end_date TEXT,
  percent_complete REAL NOT NULL DEFAULT 0,
  quantity REAL NOT NULL DEFAULT 0,
  hours REAL NOT NULL DEFAULT 0,
  rate REAL NOT NULL DEFAULT 0,
  amount REAL NOT NULL DEFAULT 0,
  billable INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'OPEN',
  created_by TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now')),
  UNIQUE(project_document_id,line_no)
);

CREATE TABLE IF NOT EXISTS erp_eam_documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_record_id INTEGER NOT NULL UNIQUE REFERENCES erp_module_records(id),
  module_code TEXT NOT NULL,
  document_no TEXT NOT NULL UNIQUE,
  document_type TEXT NOT NULL,
  equipment_code TEXT,
  serial_no TEXT,
  equipment_category TEXT,
  model TEXT,
  location_code TEXT,
  maintenance_plan TEXT,
  work_order_no TEXT,
  fault_code TEXT,
  priority TEXT,
  scheduled_start TEXT,
  scheduled_end TEXT,
  actual_start TEXT,
  actual_end TEXT,
  downtime_hours REAL NOT NULL DEFAULT 0,
  meter_reading REAL NOT NULL DEFAULT 0,
  estimated_cost REAL NOT NULL DEFAULT 0,
  actual_cost REAL NOT NULL DEFAULT 0,
  assigned_team TEXT,
  status TEXT NOT NULL,
  finance_event_id INTEGER REFERENCES erp_finance_source_events(id),
  created_by TEXT NOT NULL,
  updated_by TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_erp_eam_equipment ON erp_eam_documents(equipment_code,status,scheduled_start);
CREATE TABLE IF NOT EXISTS erp_eam_lines (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  eam_document_id INTEGER NOT NULL REFERENCES erp_eam_documents(id) ON DELETE RESTRICT,
  line_no INTEGER NOT NULL,
  line_type TEXT NOT NULL DEFAULT 'TASK',
  item_id INTEGER REFERENCES erp_items(id),
  item_code TEXT,
  description TEXT NOT NULL,
  technician TEXT,
  quantity REAL NOT NULL DEFAULT 0,
  hours REAL NOT NULL DEFAULT 0,
  unit_cost REAL NOT NULL DEFAULT 0,
  amount REAL NOT NULL DEFAULT 0,
  result_code TEXT,
  status TEXT NOT NULL DEFAULT 'OPEN',
  created_by TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now')),
  UNIQUE(eam_document_id,line_no)
);

CREATE TABLE IF NOT EXISTS erp_facility_documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_record_id INTEGER NOT NULL UNIQUE REFERENCES erp_module_records(id),
  module_code TEXT NOT NULL,
  document_no TEXT NOT NULL UNIQUE,
  document_type TEXT NOT NULL,
  site_code TEXT,
  site_name TEXT,
  customer_name TEXT,
  contract_no TEXT,
  assessment_type TEXT,
  risk_level TEXT,
  score REAL NOT NULL DEFAULT 0,
  capacity REAL NOT NULL DEFAULT 0,
  utilization_pct REAL NOT NULL DEFAULT 0,
  contract_start TEXT,
  contract_end TEXT,
  service_level TEXT,
  contract_value REAL NOT NULL DEFAULT 0,
  labor_amount REAL NOT NULL DEFAULT 0,
  material_amount REAL NOT NULL DEFAULT 0,
  percent_complete REAL NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  created_by TEXT NOT NULL,
  updated_by TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS erp_facility_lines (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  facility_document_id INTEGER NOT NULL REFERENCES erp_facility_documents(id) ON DELETE RESTRICT,
  line_no INTEGER NOT NULL,
  line_type TEXT NOT NULL DEFAULT 'RESOURCE',
  reference_code TEXT,
  description TEXT NOT NULL,
  resource_type TEXT,
  quantity REAL NOT NULL DEFAULT 0,
  hours REAL NOT NULL DEFAULT 0,
  rate REAL NOT NULL DEFAULT 0,
  amount REAL NOT NULL DEFAULT 0,
  start_date TEXT,
  end_date TEXT,
  status TEXT NOT NULL DEFAULT 'PLANNED',
  created_by TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now')),
  UNIQUE(facility_document_id,line_no)
);

CREATE TABLE IF NOT EXISTS erp_logistics_documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_record_id INTEGER NOT NULL UNIQUE REFERENCES erp_module_records(id),
  module_code TEXT NOT NULL,
  document_no TEXT NOT NULL UNIQUE,
  document_type TEXT NOT NULL,
  trip_no TEXT,
  warehouse_order_no TEXT,
  hub_code TEXT,
  vehicle_no TEXT,
  driver_name TEXT,
  carrier_name TEXT,
  route_text TEXT,
  origin_code TEXT,
  destination_code TEXT,
  pickup_at TEXT,
  delivery_at TEXT,
  distance_km REAL NOT NULL DEFAULT 0,
  odometer_km REAL NOT NULL DEFAULT 0,
  freight_amount REAL NOT NULL DEFAULT 0,
  capacity REAL NOT NULL DEFAULT 0,
  utilization_pct REAL NOT NULL DEFAULT 0,
  severity TEXT,
  status TEXT NOT NULL,
  finance_event_id INTEGER REFERENCES erp_finance_source_events(id),
  created_by TEXT NOT NULL,
  updated_by TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS erp_logistics_stops (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  logistics_document_id INTEGER NOT NULL REFERENCES erp_logistics_documents(id) ON DELETE RESTRICT,
  stop_no INTEGER NOT NULL,
  stop_type TEXT NOT NULL DEFAULT 'DELIVERY',
  location_code TEXT,
  address TEXT,
  planned_at TEXT,
  actual_at TEXT,
  reference_no TEXT,
  contact_name TEXT,
  quantity REAL NOT NULL DEFAULT 0,
  proof_reference TEXT,
  status TEXT NOT NULL DEFAULT 'PLANNED',
  created_by TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now')),
  UNIQUE(logistics_document_id,stop_no)
);

CREATE TABLE IF NOT EXISTS erp_hcm_documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_record_id INTEGER NOT NULL UNIQUE REFERENCES erp_module_records(id),
  module_code TEXT NOT NULL,
  document_no TEXT NOT NULL UNIQUE,
  document_type TEXT NOT NULL,
  employee_no TEXT,
  employee_name TEXT,
  position_title TEXT,
  department_code TEXT,
  manager_name TEXT,
  employment_type TEXT,
  hire_date TEXT,
  separation_date TEXT,
  requisition_no TEXT,
  candidate_name TEXT,
  recruitment_stage TEXT,
  pay_period TEXT,
  basic_pay REAL NOT NULL DEFAULT 0,
  allowances REAL NOT NULL DEFAULT 0,
  deductions REAL NOT NULL DEFAULT 0,
  net_pay REAL NOT NULL DEFAULT 0,
  payment_date TEXT,
  rating REAL NOT NULL DEFAULT 0,
  required_headcount REAL NOT NULL DEFAULT 0,
  current_headcount REAL NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  finance_event_id INTEGER REFERENCES erp_finance_source_events(id),
  created_by TEXT NOT NULL,
  updated_by TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_erp_hcm_employee ON erp_hcm_documents(employee_no,module_code,status);
CREATE TABLE IF NOT EXISTS erp_hcm_lines (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  hcm_document_id INTEGER NOT NULL REFERENCES erp_hcm_documents(id) ON DELETE RESTRICT,
  line_no INTEGER NOT NULL,
  line_type TEXT NOT NULL DEFAULT 'PAY_COMPONENT',
  component_code TEXT,
  description TEXT NOT NULL,
  quantity REAL NOT NULL DEFAULT 0,
  rate REAL NOT NULL DEFAULT 0,
  earning_amount REAL NOT NULL DEFAULT 0,
  deduction_amount REAL NOT NULL DEFAULT 0,
  employer_amount REAL NOT NULL DEFAULT 0,
  taxable INTEGER NOT NULL DEFAULT 1,
  statutory INTEGER NOT NULL DEFAULT 0,
  project_code TEXT,
  work_date TEXT,
  hours REAL NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'OPEN',
  created_by TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now')),
  UNIQUE(hcm_document_id,line_no)
);

CREATE TABLE IF NOT EXISTS erp_srp_documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_record_id INTEGER NOT NULL UNIQUE REFERENCES erp_module_records(id),
  module_code TEXT NOT NULL,
  document_no TEXT NOT NULL UNIQUE,
  document_type TEXT NOT NULL,
  client_name TEXT,
  opportunity_no TEXT,
  proposal_no TEXT,
  contract_no TEXT,
  sow_no TEXT,
  project_code TEXT,
  employee_no TEXT,
  billing_period TEXT,
  billing_basis TEXT,
  probability_pct REAL NOT NULL DEFAULT 0,
  estimated_cost REAL NOT NULL DEFAULT 0,
  contract_value REAL NOT NULL DEFAULT 0,
  budget_amount REAL NOT NULL DEFAULT 0,
  forecast_amount REAL NOT NULL DEFAULT 0,
  actual_amount REAL NOT NULL DEFAULT 0,
  billable_amount REAL NOT NULL DEFAULT 0,
  recognized_revenue REAL NOT NULL DEFAULT 0,
  tax_amount REAL NOT NULL DEFAULT 0,
  due_date TEXT,
  status TEXT NOT NULL,
  finance_event_id INTEGER REFERENCES erp_finance_source_events(id),
  created_by TEXT NOT NULL,
  updated_by TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS erp_srp_lines (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  srp_document_id INTEGER NOT NULL REFERENCES erp_srp_documents(id) ON DELETE RESTRICT,
  line_no INTEGER NOT NULL,
  line_type TEXT NOT NULL DEFAULT 'SERVICE',
  reference_code TEXT,
  description TEXT NOT NULL,
  employee_no TEXT,
  resource_role TEXT,
  work_date TEXT,
  quantity REAL NOT NULL DEFAULT 0,
  hours REAL NOT NULL DEFAULT 0,
  rate REAL NOT NULL DEFAULT 0,
  cost_amount REAL NOT NULL DEFAULT 0,
  billable_amount REAL NOT NULL DEFAULT 0,
  tax_amount REAL NOT NULL DEFAULT 0,
  billable INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'OPEN',
  created_by TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now')),
  UNIQUE(srp_document_id,line_no)
);

CREATE TABLE IF NOT EXISTS erp_finance_specialist_documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_record_id INTEGER NOT NULL UNIQUE REFERENCES erp_module_records(id),
  module_code TEXT NOT NULL,
  document_no TEXT NOT NULL UNIQUE,
  document_type TEXT NOT NULL,
  reporting_entity TEXT,
  fiscal_period TEXT,
  fund_code TEXT,
  grantor TEXT,
  restriction_text TEXT,
  source_balance REAL NOT NULL DEFAULT 0,
  consolidated_balance REAL NOT NULL DEFAULT 0,
  available_balance REAL NOT NULL DEFAULT 0,
  utilized_amount REAL NOT NULL DEFAULT 0,
  start_date TEXT,
  expiry_date TEXT,
  status TEXT NOT NULL,
  finance_event_id INTEGER REFERENCES erp_finance_source_events(id),
  created_by TEXT NOT NULL,
  updated_by TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS erp_finance_specialist_lines (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  finance_document_id INTEGER NOT NULL REFERENCES erp_finance_specialist_documents(id) ON DELETE RESTRICT,
  line_no INTEGER NOT NULL,
  entity_code TEXT,
  account_code TEXT,
  counterparty_code TEXT,
  description TEXT NOT NULL,
  debit REAL NOT NULL DEFAULT 0,
  credit REAL NOT NULL DEFAULT 0,
  amount REAL NOT NULL DEFAULT 0,
  elimination_type TEXT,
  fund_code TEXT,
  status TEXT NOT NULL DEFAULT 'OPEN',
  created_by TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now')),
  UNIQUE(finance_document_id,line_no)
);

CREATE TABLE IF NOT EXISTS erp_platform_integrations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_record_id INTEGER UNIQUE REFERENCES erp_module_records(id),
  module_code TEXT NOT NULL,
  integration_code TEXT NOT NULL UNIQUE,
  integration_name TEXT NOT NULL,
  integration_type TEXT NOT NULL,
  endpoint_reference TEXT,
  authentication_type TEXT,
  direction TEXT NOT NULL DEFAULT 'BIDIRECTIONAL',
  schedule_expression TEXT,
  last_run_at TEXT,
  last_status TEXT,
  records_processed INTEGER NOT NULL DEFAULT 0,
  error_count INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 0,
  created_by TEXT NOT NULL,
  updated_by TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS erp_platform_integration_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  integration_id INTEGER NOT NULL REFERENCES erp_platform_integrations(id),
  run_no TEXT NOT NULL UNIQUE,
  started_at TEXT NOT NULL DEFAULT (datetime('now')),
  completed_at TEXT,
  status TEXT NOT NULL DEFAULT 'RUNNING',
  records_read INTEGER NOT NULL DEFAULT 0,
  records_written INTEGER NOT NULL DEFAULT 0,
  error_count INTEGER NOT NULL DEFAULT 0,
  error_message TEXT,
  initiated_by TEXT NOT NULL
);

INSERT OR IGNORE INTO erp_chart_accounts(account_code,account_name,account_type,financial_statement,normal_balance,parent_account_code,control_type,cash_flow_group,system_account,allow_manual_posting) VALUES
('1230','Work in Process Inventory','ASSET','BALANCE_SHEET','DEBIT','1200','WIP','OPERATING',1,0),
('1240','Finished Goods Inventory','ASSET','BALANCE_SHEET','DEBIT','1200','FINISHED_GOODS','OPERATING',1,0),
('1110','Contract Assets and Unbilled Receivables','ASSET','BALANCE_SHEET','DEBIT','1100','CONTRACT_ASSET','OPERATING',1,0),
('2230','Employee Reimbursements Payable','LIABILITY','BALANCE_SHEET','CREDIT','2200','EMPLOYEE_PAYABLE','OPERATING',1,0),
('2240','Statutory and Other Payroll Deductions Payable','LIABILITY','BALANCE_SHEET','CREDIT','2200','PAYROLL_DEDUCTION','OPERATING',1,0),
('4040','Project and Service Revenue','REVENUE','INCOME_STATEMENT','CREDIT','4000','PROJECT_REVENUE','OPERATING',0,1),
('5100','Production Conversion Cost','EXPENSE','INCOME_STATEMENT','DEBIT','5000','PRODUCTION_COST','OPERATING',0,1),
('6510','Maintenance Materials and Services','EXPENSE','INCOME_STATEMENT','DEBIT','6500','MAINTENANCE_COST','OPERATING',0,1),
('6520','Project Delivery Cost','EXPENSE','INCOME_STATEMENT','DEBIT','6500','PROJECT_COST','OPERATING',0,1),
('6530','Freight and Logistics Cost','EXPENSE','INCOME_STATEMENT','DEBIT','6500','LOGISTICS_COST','OPERATING',0,1),
('6540','Training and Employee Development','EXPENSE','INCOME_STATEMENT','DEBIT','6500','HCM_COST','OPERATING',0,1);

-- Map every enterprise menu module to a specialist or existing core transaction engine.
INSERT OR REPLACE INTO erp_specialist_module_config(module_code,domain_code,engine_code,line_engine_code,finance_event_type,requires_lines,rollout_level,notes) VALUES
('fa-general-accounting','FINANCE','CORE_FINANCE',NULL,NULL,0,'CORE','Journal and period-control engine'),
('fa-receivables-payables','FINANCE','CORE_SUBLEDGER',NULL,NULL,0,'CORE','AR/AP and cash application engine'),
('fa-fixed-assets','FINANCE','CORE_FIXED_ASSET',NULL,NULL,0,'CORE','Asset books and depreciation engine'),
('fa-management-accounting','FINANCE','FINANCE_SPECIALIST','FINANCE_LINES',NULL,0,'SPECIALIST','Cost center and management accounting controls'),
('fa-consolidation-reporting','FINANCE','FINANCE_SPECIALIST','FINANCE_LINES',NULL,1,'SPECIALIST','Entity close, consolidation and eliminations'),
('fa-financial-services','FINANCE','CORE_BANKING',NULL,NULL,0,'CORE','Banking and reconciliation engine'),
('fa-planning-budgeting','FINANCE','CORE_PLANNING',NULL,NULL,0,'CORE','Budget and forecast engine'),
('fa-grants-funds','FINANCE','FINANCE_SPECIALIST','FINANCE_LINES','FUND_UTILIZATION',0,'SPECIALIST','Restricted fund and grant controls'),
('sd-crm','CRM','CRM_PIPELINE',NULL,NULL,0,'SPECIALIST','Lead, opportunity and account activity pipeline'),
('sd-demand-planning','SALES','CORE_PLANNING',NULL,NULL,0,'CORE','Demand plan connected to inventory planning'),
('sd-order-management','SALES','CORE_SALES',NULL,NULL,0,'CORE','Sales and lease order transaction engine'),
('sd-lease-contract-management','SALES','CORE_LEASE',NULL,NULL,0,'CORE','Serialized lease contract engine'),
('sd-outbound-logistics','SALES','CORE_DELIVERY',NULL,NULL,0,'CORE','Delivery, POD and return obligations'),
('sd-warranty-management','QUALITY','QUALITY','QUALITY_RESULTS',NULL,1,'SPECIALIST','Warranty registration, claims and replacement control'),
('sd-service-management','EAM','EAM','EAM_LINES','MAINTENANCE_COST',1,'SPECIALIST','Service tickets and repair jobs'),
('sd-pim','SUPPLY','CORE_ITEM_MASTER',NULL,NULL,0,'CORE','Item master and product information'),
('sd-customer-portal','CRM','CRM_PIPELINE',NULL,NULL,0,'SPECIALIST','Customer requests, cases and account records'),
('ip-inventory-analysis','SUPPLY','CORE_INVENTORY',NULL,NULL,0,'CORE','Inventory analysis and valuation'),
('ip-warehouse-management','SUPPLY','CORE_INVENTORY',NULL,NULL,0,'CORE','Serial warehouse and movement engine'),
('ip-cycle-counting','SUPPLY','CORE_CYCLE_COUNT',NULL,NULL,0,'CORE','Physical count and variance engine'),
('ip-sourcing-purchasing','SUPPLY','CORE_PROCUREMENT',NULL,NULL,0,'CORE','Sourcing, PO, GRNI and AP engine'),
('ip-inbound-logistics','SUPPLY','CORE_INBOUND',NULL,NULL,0,'CORE','ATLAS/STELLAR shipment and receipt engine'),
('ip-subcontracting','MANUFACTURING','MANUFACTURING','MANUFACTURING_LINES','PROJECT_COST',1,'SPECIALIST','External processing and service materials'),
('ip-supplier-portal','SUPPLY','CORE_PARTNER_PORTAL',NULL,NULL,0,'CORE','Supplier master and shipment visibility'),
('mf-estimation','MANUFACTURING','MANUFACTURING','MANUFACTURING_LINES',NULL,1,'SPECIALIST','BOM and conversion estimate'),
('mf-planning','MANUFACTURING','MANUFACTURING','MANUFACTURING_LINES',NULL,1,'SPECIALIST','MRP, production and capacity planning'),
('mf-work-orders','MANUFACTURING','MANUFACTURING','MANUFACTURING_LINES','MANUFACTURING_OUTPUT',1,'SPECIALIST','Production work-order control'),
('mf-scheduling','MANUFACTURING','MANUFACTURING','MANUFACTURING_LINES',NULL,1,'SPECIALIST','Resource and work-center scheduling'),
('mf-execution','MANUFACTURING','MANUFACTURING','MANUFACTURING_LINES','MANUFACTURING_OUTPUT',1,'SPECIALIST','Material issue, operation confirmation and output'),
('mf-costing','MANUFACTURING','MANUFACTURING','MANUFACTURING_LINES',NULL,1,'SPECIALIST','Standard, actual and variance costing'),
('qm-attributes','QUALITY','QUALITY','QUALITY_RESULTS',NULL,1,'SPECIALIST','Specifications, attributes and tolerances'),
('qm-inspection-sampling','QUALITY','QUALITY','QUALITY_RESULTS',NULL,1,'SPECIALIST','Inspection and sampling plans'),
('qm-administration','QUALITY','QUALITY','QUALITY_RESULTS',NULL,1,'SPECIALIST','Incoming, process and final inspection'),
('qm-acceptance-rejection','QUALITY','QUALITY','QUALITY_RESULTS',NULL,1,'SPECIALIST','Disposition, deviation and supplier return'),
('pm-planning-budgeting','PROJECTS','PROJECT','PROJECT_LINES',NULL,1,'SPECIALIST','Project budget and forecast'),
('pm-definition','PROJECTS','PROJECT','PROJECT_LINES',NULL,1,'SPECIALIST','Project charter, WBS and ownership'),
('pm-tracking','PROJECTS','PROJECT','PROJECT_LINES',NULL,1,'SPECIALIST','Milestones, risks, issues and changes'),
('pm-billing','PROJECTS','PROJECT','PROJECT_LINES','PROJECT_BILLING',1,'SPECIALIST','Milestone and progress billing'),
('pm-closure','PROJECTS','PROJECT','PROJECT_LINES',NULL,1,'SPECIALIST','Operational and financial closure'),
('eam-induction-setup','EAM','EAM','EAM_LINES',NULL,0,'SPECIALIST','Equipment registry and induction'),
('eam-preventive-maintenance','EAM','EAM','EAM_LINES',NULL,1,'SPECIALIST','Preventive maintenance plans'),
('eam-online-maintenance','EAM','EAM','EAM_LINES','MAINTENANCE_COST',1,'SPECIALIST','Breakdown and corrective request'),
('eam-shutdown-outage','EAM','EAM','EAM_LINES',NULL,1,'SPECIALIST','Shutdown, outage and restart planning'),
('eam-work-management','EAM','EAM','EAM_LINES','MAINTENANCE_COST',1,'SPECIALIST','Corrective and preventive work orders'),
('eam-reliability-review','EAM','EAM','EAM_LINES',NULL,1,'SPECIALIST','Failure and reliability analysis'),
('eam-equipment-rental','EAM','EAM','EAM_LINES','PROJECT_BILLING',1,'SPECIALIST','Rental dispatch, return and billing'),
('fm-assessment','FACILITY','FACILITY','FACILITY_LINES',NULL,1,'SPECIALIST','Site and compliance assessments'),
('fm-quotation','FACILITY','FACILITY','FACILITY_LINES',NULL,1,'SPECIALIST','Facility service quotation'),
('fm-contracts','FACILITY','FACILITY','FACILITY_LINES',NULL,1,'SPECIALIST','FM contracts and SLA controls'),
('fm-site-administration','FACILITY','FACILITY','FACILITY_LINES',NULL,0,'SPECIALIST','Site master and operating controls'),
('fm-resource-allocation','FACILITY','FACILITY','FACILITY_LINES',NULL,1,'SPECIALIST','People, equipment and space allocation'),
('fm-work-reporting','FACILITY','FACILITY','FACILITY_LINES','MAINTENANCE_COST',1,'SPECIALIST','Daily work and maintenance reporting'),
('lm-transport','LOGISTICS','LOGISTICS','LOGISTICS_STOPS',NULL,1,'SPECIALIST','Transport order, route and POD'),
('lm-order-warehouse','LOGISTICS','LOGISTICS','LOGISTICS_STOPS',NULL,1,'SPECIALIST','Picking, packing, staging and dispatch'),
('lm-hub-management','LOGISTICS','LOGISTICS','LOGISTICS_STOPS',NULL,0,'SPECIALIST','Distribution and service hub control'),
('lm-command-center','LOGISTICS','LOGISTICS','LOGISTICS_STOPS',NULL,0,'SPECIALIST','Exception and capacity command center'),
('lm-contracting-billing','LOGISTICS','LOGISTICS','LOGISTICS_STOPS','TRANSPORT_BILL',1,'SPECIALIST','Carrier contracts, rates and freight billing'),
('lm-fleet-management','LOGISTICS','LOGISTICS','LOGISTICS_STOPS','MAINTENANCE_COST',1,'SPECIALIST','Fleet, fuel, service and incidents'),
('hcm-workforce','HCM','HCM','HCM_LINES',NULL,0,'SPECIALIST','Employee master, assignment and separation'),
('hcm-recruitment','HCM','HCM','HCM_LINES',NULL,1,'SPECIALIST','Requisition, applicant, interview and onboarding'),
('hcm-talent','HCM','HCM','HCM_LINES',NULL,1,'SPECIALIST','Goals, reviews and succession'),
('hcm-development','HCM','HCM','HCM_LINES','EMPLOYEE_DEVELOPMENT_COST',1,'SPECIALIST','Learning, certification and development'),
('hcm-payroll-benefits','HCM','HCM','HCM_LINES','PAYROLL_DETAILED',1,'SPECIALIST','Configurable payroll components and benefit lines'),
('hcm-workforce-planning','HCM','HCM','HCM_LINES',NULL,1,'SPECIALIST','Headcount, hiring, shift and capacity plan'),
('srp-proposal-estimation','SRP','SRP','SRP_LINES',NULL,1,'SPECIALIST','Proposal costing and commercial offer'),
('srp-rates-contracts','SRP','SRP','SRP_LINES',NULL,1,'SPECIALIST','Rate card and contract pricing'),
('srp-sow-project','SRP','SRP','SRP_LINES',NULL,1,'SPECIALIST','SOW, work packages and change orders'),
('srp-timesheet','SRP','SRP','SRP_LINES',NULL,1,'SPECIALIST','Project time and approval'),
('srp-expense','SRP','SRP','SRP_LINES','EXPENSE_REIMBURSEMENT',1,'SPECIALIST','Expense, reimbursement and CA liquidation'),
('srp-billing-revenue','SRP','SRP','SRP_LINES','PROJECT_BILLING',1,'SPECIALIST','Billing and revenue recognition'),
('srp-budgets','SRP','SRP','SRP_LINES',NULL,1,'SPECIALIST','SOW budget, forecast and variance'),
('srp-resource-bench','SRP','SRP','SRP_LINES',NULL,1,'SPECIALIST','Resource availability, skill and allocation'),
('tool-advanced-reporting','PLATFORM','PLATFORM_INTEGRATION',NULL,NULL,0,'PLATFORM','Report definitions and scheduled output'),
('tool-wizard-interface','PLATFORM','PLATFORM_INTEGRATION',NULL,NULL,0,'PLATFORM','Guided process configuration'),
('tool-embedded-workflow','PLATFORM','PLATFORM_INTEGRATION',NULL,NULL,0,'PLATFORM','Workflow and approval configuration'),
('tool-data-uploads','PLATFORM','PLATFORM_INTEGRATION',NULL,NULL,0,'PLATFORM','Controlled import and validation'),
('addon-analytics','PLATFORM','PLATFORM_INTEGRATION',NULL,NULL,0,'PLATFORM','Analytics publishing'),
('addon-mobility','PLATFORM','PLATFORM_INTEGRATION',NULL,NULL,0,'PLATFORM','Mobile access configuration'),
('addon-extension-toolkit','PLATFORM','PLATFORM_INTEGRATION',NULL,NULL,0,'PLATFORM','Extension registry'),
('addon-esignature','PLATFORM','PLATFORM_INTEGRATION',NULL,NULL,0,'PLATFORM','eSignature provider integration'),
('addon-device-integration','PLATFORM','PLATFORM_INTEGRATION',NULL,NULL,0,'PLATFORM','Device and telemetry integration'),
('addon-soa-collaboration','PLATFORM','PLATFORM_INTEGRATION',NULL,NULL,0,'PLATFORM','API and collaboration integration'),
('addon-planning-optimization','PLATFORM','PLATFORM_INTEGRATION',NULL,NULL,0,'PLATFORM','Optimization service configuration');

-- Default approval authority can be overridden by module, document type, department and amount.
INSERT OR IGNORE INTO erp_approval_matrices(matrix_code,module_code,document_type,department,amount_from,amount_to,step_no,approver_role_code,action_code,created_by) VALUES
('APR-DEFAULT-001','*','*','*',0,100000,1,'SCM_MANAGER','APPROVE','system'),
('APR-DEFAULT-002','*','*','*',100000.01,1000000,1,'FINANCE','APPROVE','system'),
('APR-DEFAULT-003','*','*','*',1000000.01,NULL,1,'ADMIN','APPROVE','system');

CREATE VIEW IF NOT EXISTS vw_erp_pending_approvals AS
SELECT a.id,a.module_code,a.record_id,a.record_no,a.cycle_no,a.step_no,a.required_role_code,a.assigned_user_id,
       a.action_code,a.status,a.requested_by,a.requested_at,r.record_type,r.department,r.amount,r.owner_email,
       u.email assigned_user_email,u.display_name assigned_user_name
FROM erp_workflow_approvals a
JOIN erp_module_records r ON r.id=a.record_id
LEFT JOIN erp_users u ON u.id=a.assigned_user_id
WHERE a.status='PENDING';

CREATE VIEW IF NOT EXISTS vw_erp_rollout_module_readiness AS
SELECT c.module_code,c.domain_code,c.engine_code,c.line_engine_code,c.finance_event_type,
       c.requires_lines,c.rollout_level,c.active,
       COUNT(DISTINCT r.id) record_count,
       SUM(CASE WHEN r.status IN ('FOR_APPROVAL','SUBMITTED','BASELINE') THEN 1 ELSE 0 END) pending_approval,
       SUM(CASE WHEN r.status IN ('POSTED','ACTIVE','CLOSED','COMPLETED') THEN 1 ELSE 0 END) completed_records
FROM erp_specialist_module_config c
LEFT JOIN erp_module_records r ON r.module_code=c.module_code
GROUP BY c.module_code,c.domain_code,c.engine_code,c.line_engine_code,c.finance_event_type,
         c.requires_lines,c.rollout_level,c.active;

CREATE VIEW IF NOT EXISTS vw_erp_enterprise_document_flow AS
SELECT l.id,l.source_module_code,l.source_record_id,l.source_record_no,l.link_type,l.shared_reference,
       l.target_module_code,l.target_record_id,l.target_record_no,l.status,l.created_at
FROM erp_enterprise_record_links l
WHERE l.status='ACTIVE';


-- Version 13 rollout settings
INSERT OR REPLACE INTO erp_settings(key,value,updated_at) VALUES
('APP_VERSION','13.0.0-rollout-specialist',datetime('now')),
('SYSTEM_BUILD_MODE','ROLLOUT_SPECIALIST_INTERCONNECTED_ERP',datetime('now')),
('MODULE_ENGINE_POLICY','CORE_OR_SPECIALIST_OR_PLATFORM_ONLY',datetime('now')),
('APPROVAL_POLICY','AMOUNT_ROLE_AND_SEGREGATION_OF_DUTIES',datetime('now')),
('ROLLOUT_CANDIDATE','YES',datetime('now'));
