-- 0060 · The sales register, all of it, and the money that came in
--
-- Generated by scripts/generate-sales-collections.py. Do not hand-edit.
--
-- Most of the workbook was never loaded - three of twenty-two motorcycle
-- sales, forty-nine of sixty-eight after-sales rows - and none of the
-- receipts were, which is why collection read zero against three and a
-- half million pesos of billings. Every row carries a deposit date, a
-- method and a bank: the customers had paid.
--
-- After-sales, warehouse service and motorcycle sales are posted.
-- Leases and battery swapping stay as drafts for review.
--
-- Part 2 of 2.

UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),NULL),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'PENDING' ELSE cleared_status END WHERE source_key='SM:MCLeased:33';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),NULL),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'PENDING' ELSE cleared_status END WHERE source_key='SM:MCLeased:34';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),'2026-06-27'),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'CLEARED' ELSE cleared_status END WHERE source_key='SM:MCLeased:35';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),'2026-06-25'),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'CLEARED' ELSE cleared_status END WHERE source_key='SM:MCLeased:36';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),'2026-06-28'),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'CLEARED' ELSE cleared_status END WHERE source_key='SM:MCLeased:38';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),'2026-02-28'),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'CLEARED' ELSE cleared_status END WHERE source_key='SM:BSwapping:6';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),'2026-05-05'),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'CLEARED' ELSE cleared_status END WHERE source_key='SM:BSwapping:7';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),'2026-05-28'),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'CLEARED' ELSE cleared_status END WHERE source_key='SM:BSwapping:8';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),'2026-05-28'),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'CLEARED' ELSE cleared_status END WHERE source_key='SM:BSwapping:9';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),'2026-05-28'),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'CLEARED' ELSE cleared_status END WHERE source_key='SM:BSwapping:10';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),'5/28 ; 6/23'),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'CLEARED' ELSE cleared_status END WHERE source_key='SM:BSwapping:11';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),'2026-06-23'),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'CLEARED' ELSE cleared_status END WHERE source_key='SM:BSwapping:12';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),NULL),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'PENDING' ELSE cleared_status END WHERE source_key='SM:BSwapping:13';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),NULL),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'PENDING' ELSE cleared_status END WHERE source_key='SM:BSwapping:14';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),NULL),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'PENDING' ELSE cleared_status END WHERE source_key='SM:BSwapping:15';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),NULL),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'PENDING' ELSE cleared_status END WHERE source_key='SM:BSwapping:16';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),NULL),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'PENDING' ELSE cleared_status END WHERE source_key='SM:BSwapping:17';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),NULL),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'PENDING' ELSE cleared_status END WHERE source_key='SM:BSwapping:18';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),NULL),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'PENDING' ELSE cleared_status END WHERE source_key='SM:BSwapping:19';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),NULL),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'PENDING' ELSE cleared_status END WHERE source_key='SM:BSwapping:20';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),NULL),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'PENDING' ELSE cleared_status END WHERE source_key='SM:BSwapping:21';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),NULL),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'PENDING' ELSE cleared_status END WHERE source_key='SM:BSwapping:22';
UPDATE erp_ar_collections SET payment_method=COALESCE(NULLIF(payment_method,''),NULL),bank_wallet=COALESCE(NULLIF(bank_wallet,''),NULL),bank_ref=COALESCE(NULLIF(bank_ref,''),NULL),settlement_date=COALESCE(NULLIF(settlement_date,''),NULL),cleared_status=CASE WHEN cleared_status='PENDING' THEN 'PENDING' ELSE cleared_status END WHERE source_key='SM:BSwapping:23';

UPDATE erp_ar_collections SET status='POSTED',
       posted_by='sales-register@nrdev.ph', posted_at=datetime('now'),
       updated_at=datetime('now')
 WHERE source_system='SALES_MONITORING_2026' AND status='DRAFT'
   AND stream IN ('AFTERSALES','WAREHOUSE_SERVICE','MC_SOLD');

INSERT INTO erp_ar_receipts(receipt_no,collection_id,entry_no,receipt_date,amount,
  payment_method,bank_wallet,bank_ref,or_no,settlement_date,cleared_status,remarks,
  status,received_by)
SELECT 'OR-SM-'||printf('%05d',c.id), c.id, c.entry_no,
       c.settlement_date, c.gross_amount,
       c.payment_method, c.bank_wallet, c.bank_ref, c.document_no, c.settlement_date,
       CASE WHEN COALESCE(c.cleared_status,'PENDING')='PENDING' THEN 'CLEARED'
            ELSE c.cleared_status END,
       'Received per the 2026 sales monitoring sheet.', 'ACTIVE', 'sales-register@nrdev.ph'
  FROM erp_ar_collections c
 WHERE c.status='POSTED' AND COALESCE(c.settlement_date,'')<>'' AND c.gross_amount>0
   AND NOT EXISTS (SELECT 1 FROM erp_ar_receipts r
                    WHERE r.collection_id=c.id AND r.status<>'VOID');

