"""
Loads the sales monitoring workbook properly: every row, and the money received.

Two things were wrong with the register as it stood.

The first is that most of it was never loaded. The workbook holds 22 motorcycle
sales worth PHP 7.2m; three were in the system. After-sales had 49 of its 68
rows. Nobody could have seen that from the screen, because a register with a
hundred rows in it looks like a register.

The second is that the money was never recorded. Every row of the workbook
carries a Deposit / Settlement Date, a payment method and a bank or wallet -
which is to say the customer had already paid. Loading the sale and not the
receipt is why the collection rate read zero against three and a half million
pesos of billings: the billing side was there and the collecting side was not.

So this regenerates the register from the workbook, and for every row the sheet
says was settled it records the receipt as well.

What is posted and what is left alone:

  After-sales, warehouse service and motorcycle sales are posted. Those are the
  three Alexis asked for.

  Leases and battery swapping stay as drafts, because those are the two she
  said she would review herself.

Idempotent on a source key of sheet and row, so the deploy can run it every
time. The rows the earlier import already created are matched and given the
same key rather than loaded twice.

    python3 scripts/generate-sales-collections.py
"""
import datetime
from collections import defaultdict

import openpyxl

SRC = 'source_data/E88_SalesMonitoring_2026.xlsx'
OUT = 'migrations/0060_sales_collections.sql'

# Sheet -> the stream the system files it under, and whether Finance has
# already told us to post it.
SHEETS = [
    ('Aftersales',       'AFTERSALES',        True),
    ('WhseServiceSales', 'WAREHOUSE_SERVICE', True),
    ('MCSales',          'MC_SOLD',           True),
    ('MCLeased',         'MC_LEASED',         False),
    ('BSwapping',        'BATTERY_SWAP',      False),
]

# Column positions, from row 5 of every sheet.
C_ENTRY, C_DATE, C_TYPE, C_DOC, C_CUST, C_CONTRACT = 0, 1, 2, 3, 4, 5
C_DEPT, C_CC, C_TITLE, C_DESC = 6, 7, 8, 9
C_GROSS, C_VATTYPE, C_VATRATE, C_NET, C_VAT = 10, 11, 12, 13, 14
C_METHOD, C_BANK, C_BANKREF, C_OTHERREF, C_SETTLED, C_CLEARED = 15, 16, 17, 18, 19, 20
C_PREPARED, C_NOTES = 21, 22


def text(v):
    if v is None:
        return ''
    if isinstance(v, datetime.datetime):
        return v.strftime('%Y-%m-%d')
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return str(v).strip()


def num(v):
    try:
        return round(float(v or 0), 2)
    except (TypeError, ValueError):
        return 0.0


def q(v):
    s = text(v)
    return 'NULL' if s == '' else "'" + s.replace("'", "''") + "'"


def main():
    wb = openpyxl.load_workbook(SRC, data_only=True)
    out = []
    w = out.append

    w("-- 0060 · The sales register, all of it, and the money that came in")
    w("--")
    w("-- Generated by scripts/generate-sales-collections.py. Do not hand-edit.")
    w("--")
    w("-- Most of the workbook was never loaded - three of twenty-two motorcycle")
    w("-- sales, forty-nine of sixty-eight after-sales rows - and none of the")
    w("-- receipts were, which is why collection read zero against three and a")
    w("-- half million pesos of billings. Every row carries a deposit date, a")
    w("-- method and a bank: the customers had paid.")
    w("--")
    w("-- After-sales, warehouse service and motorcycle sales are posted.")
    w("-- Leases and battery swapping stay as drafts for review.")
    w("--")
    w("-- Re-runnable: keyed on the sheet and row it came from.")
    w("")

    rows = []
    for sheet, stream, post in SHEETS:
        ws = wb[sheet]
        for i, r in enumerate(ws.iter_rows(min_row=6, values_only=True), start=6):
            if not r or (not text(r[C_ENTRY]) and num(r[C_GROSS]) == 0):
                continue
            gross = num(r[C_GROSS])
            if gross == 0 and not text(r[C_CUST]):
                continue
            rows.append({
                'key': f'SM:{sheet}:{i}',
                'sheet': sheet, 'stream': stream, 'post': post,
                'date': text(r[C_DATE]) or '2026-01-01',
                'type': text(r[C_TYPE]), 'doc': text(r[C_DOC]),
                'customer': text(r[C_CUST]) or 'VARIOUS CUSTOMERS',
                'contract': text(r[C_CONTRACT]),
                'dept': text(r[C_DEPT]), 'cc': text(r[C_CC]),
                'title': text(r[C_TITLE]), 'desc': text(r[C_DESC])[:400],
                'gross': gross,
                'vat_type': text(r[C_VATTYPE]) or 'VATable',
                'vat_rate': num(r[C_VATRATE]),
                'net': num(r[C_NET]) or gross,
                'vat': num(r[C_VAT]),
                'method': text(r[C_METHOD]), 'bank': text(r[C_BANK]),
                'bank_ref': text(r[C_BANKREF]), 'other_ref': text(r[C_OTHERREF]),
                'settled': text(r[C_SETTLED]),
                'cleared': text(r[C_CLEARED]) or ('CLEARED' if text(r[C_SETTLED]) else 'PENDING'),
                'prepared': text(r[C_PREPARED]), 'notes': text(r[C_NOTES])[:300],
            })

    # ---- 1. Give the rows the earlier import already created the same key ----
    w("-- The earlier import left no trace of which sheet row each entry came")
    w("-- from, so the rows it created are matched on what they say - stream,")
    w("-- date, customer and amount - and given the key. Matching first is what")
    w("-- stops this loading the same sale twice.")
    for r in rows:
        def match(p=''):
            # The alias has to go on the column, not on ROUND(), which is why
            # this is built rather than string-replaced.
            return (f"{p}stream={q(r['stream'])} AND {p}txn_date={q(r['date'])}"
                    f" AND {p}customer_name={q(r['customer'])}"
                    f" AND ROUND({p}gross_amount,2)={r['gross']}")
        w(f"UPDATE erp_ar_collections SET source_key={q(r['key'])}"
          f" WHERE source_key IS NULL AND {match()}"
          f" AND id=(SELECT MIN(x.id) FROM erp_ar_collections x"
          f" WHERE x.source_key IS NULL AND {match('x.')});")

    # ---- 2. Load whatever is still missing --------------------------------
    w("")
    w("-- And load the rows that were never there. Entry numbers continue the")
    w("-- series the register already uses.")
    for n, r in enumerate(rows, start=1):
        entry = f"AR-SM-{n:05d}"
        w("INSERT INTO erp_ar_collections(entry_no,stream,txn_date,sales_type,document_no,"
          "customer_name,contract_ref,unit_count,department,cost_center,account_title,description,"
          "gross_amount,vat_type,vat_rate,net_amount,output_vat,payment_method,bank_wallet,bank_ref,"
          "other_ref,settlement_date,cleared_status,status,prepared_by,notes,source_system,source_key,created_by)"
          f" SELECT {q(entry)},{q(r['stream'])},{q(r['date'])},{q(r['type'])},{q(r['doc'])},"
          f"{q(r['customer'])},{q(r['contract'])},0,{q(r['dept'])},{q(r['cc'])},{q(r['title'])},"
          f"{q(r['desc'])},{r['gross']},{q(r['vat_type'])},{r['vat_rate']},{r['net']},{r['vat']},"
          f"{q(r['method'])},{q(r['bank'])},{q(r['bank_ref'])},{q(r['other_ref'])},{q(r['settled'])},"
          f"{q(r['cleared'])},'DRAFT',{q(r['prepared'])},{q(r['notes'])},'SALES_MONITORING_2026',"
          f"{q(r['key'])},'import'"
          f" WHERE NOT EXISTS (SELECT 1 FROM erp_ar_collections c WHERE c.source_key={q(r['key'])});")

    # ---- 3. Fill in what the earlier import dropped -----------------------
    w("")
    w("-- The first load kept the amount but not how it was settled. Those")
    w("-- columns are what a receipt is made of, so they are filled in where")
    w("-- nobody has since typed something different.")
    for r in rows:
        sets = [f"payment_method=COALESCE(NULLIF(payment_method,''),{q(r['method'])})",
                f"bank_wallet=COALESCE(NULLIF(bank_wallet,''),{q(r['bank'])})",
                f"bank_ref=COALESCE(NULLIF(bank_ref,''),{q(r['bank_ref'])})",
                f"settlement_date=COALESCE(NULLIF(settlement_date,''),{q(r['settled'])})",
                f"cleared_status=CASE WHEN cleared_status='PENDING' THEN {q(r['cleared'])} ELSE cleared_status END"]
        w(f"UPDATE erp_ar_collections SET {','.join(sets)} WHERE source_key={q(r['key'])};")

    # ---- 4. Post the three streams Finance asked for ----------------------
    w("")
    w("-- After-sales, warehouse service and motorcycle sales are posted; the")
    w("-- leases and the swapping stay as drafts for review. A row somebody has")
    w("-- already voided is left alone.")
    w("UPDATE erp_ar_collections SET status='POSTED',")
    w("       posted_by='sales-register@nrdev.ph', posted_at=datetime('now'),")
    w("       updated_at=datetime('now')")
    w(" WHERE source_system='SALES_MONITORING_2026' AND status='DRAFT'")
    w("   AND stream IN ('AFTERSALES','WAREHOUSE_SERVICE','MC_SOLD');")

    # ---- 5. The money that came in ----------------------------------------
    w("")
    w("-- The receipt. One per settled row, at the amount the sheet says was")
    w("-- billed, carrying the method and the bank it landed in. Nothing is")
    w("-- recorded for a row the sheet never settled: those are genuinely still")
    w("-- outstanding and the register should say so.")
    w("INSERT INTO erp_ar_receipts(receipt_no,collection_id,entry_no,receipt_date,amount,")
    w("  payment_method,bank_wallet,bank_ref,or_no,settlement_date,cleared_status,remarks,")
    w("  status,received_by)")
    w("SELECT 'OR-SM-'||printf('%05d',c.id), c.id, c.entry_no,")
    w("       c.settlement_date, c.gross_amount,")
    w("       c.payment_method, c.bank_wallet, c.bank_ref, c.document_no, c.settlement_date,")
    w("       CASE WHEN COALESCE(c.cleared_status,'PENDING')='PENDING' THEN 'CLEARED'")
    w("            ELSE c.cleared_status END,")
    w("       'Received per the 2026 sales monitoring sheet.', 'ACTIVE', 'sales-register@nrdev.ph'")
    w("  FROM erp_ar_collections c")
    w(" WHERE c.status='POSTED' AND COALESCE(c.settlement_date,'')<>'' AND c.gross_amount>0")
    w("   AND NOT EXISTS (SELECT 1 FROM erp_ar_receipts r")
    w("                    WHERE r.collection_id=c.id AND r.status<>'VOID');")
    receipts = sum(1 for r in rows if r['post'] and r['settled'] and r['gross'] > 0)

    by = defaultdict(lambda: [0, 0.0, 0, 0.0])
    for r in rows:
        b = by[r['stream']]
        b[0] += 1
        b[1] += r['gross']
        if r['post'] and r['settled']:
            b[2] += 1
            b[3] += r['gross']
    w("")
    w("-- What this loads, by stream: rows, billed, receipts, received.")
    for stream in sorted(by):
        n_, g_, rn, rg = by[stream]
        w(f"--   {stream:18} {n_:4} rows  {g_:14,.2f}   {rn:4} receipts  {rg:14,.2f}")

    header = [l for l in out if l.startswith('--')][:13]
    lines = [l for l in out if not l.startswith('--')]
    CHUNK = 400
    parts = [lines[i:i + CHUNK] for i in range(0, len(lines), CHUNK)] or [[]]
    written = []
    for i, part in enumerate(parts, 1):
        name = OUT.replace('.sql', f'_{i:02d}.sql')
        with open(name, 'w', encoding='utf-8') as fh:
            fh.write('\n'.join(header + [f'-- Part {i} of {len(parts)}.', ''] + part) + '\n')
        written.append(name)

    print(f'{len(rows)} rows, {receipts} receipts')
    for stream in sorted(by):
        n_, g_, rn, rg = by[stream]
        print(f'  {stream:18} {n_:4} rows {g_:14,.2f}  {rn:4} receipts {rg:14,.2f}')
    for name in written:
        print('  ' + name)


if __name__ == '__main__':
    main()
