"""
Pulls the proof-of-payment documents out of the procurement sheet.

The bank advice for each payment is not in a column of its own. It is the
hyperlink sitting on the "BDO Payment Ref" cell, pointing at a PDF in the
company SharePoint under Payments/Proof of Payment. The cell text is the file
name, and the file name carries the date, the payee, the bank and the amount:

    01-20-26_THINGSPH INC_MBOS FT P45,688.94.pdf

So the register knew all along which payments could be evidenced. 252 of the
356 requests carry a document; 11 of those carry several, because the request
was settled in more than one go or the same advice covers more than one line.

This writes migrations/0056_proof_of_payment_*.sql, which:

  * links each document to its request as a PAYMENT_PROOF attachment,
  * puts a request that carries a document but was never marked paid onto PAID,
  * gives every paid request a settlement if 0055 has not already,
  * and points each settlement at its document, with the date read off the
    file name where the sheet never recorded one.

The amount in the file name is deliberately NOT used to set the settlement
amount: an advice frequently covers several requests, so the figure on the
document and the figure on the request are different questions.

    python3 scripts/generate-proof-of-payment.py
"""
import datetime
import re
from collections import defaultdict

import openpyxl

SRC = 'source_data/E88_ProcurementMonitoring_2026.xlsx'
OUT = 'migrations/0056_proof_of_payment.sql'
IMPORT_ACTOR = 'procurement-register@nrdev.ph'

# The 30% down payment on the Ampace supply order. It has no advice yet and it
# is not settled in full, so nothing here may push it onto PAID.
PARTIAL = {'RFP-OPS2026-00101'}

DATE_IN_NAME = re.compile(r'^(\d{2})-(\d{2})-(\d{2})_')


def text(v):
    if v is None:
        return ''
    if isinstance(v, datetime.datetime):
        return v.strftime('%Y-%m-%d')
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return str(v).strip()


def q(v):
    s = text(v)
    return 'NULL' if s == '' else "'" + s.replace("'", "''") + "'"


def paid_date_of(file_name):
    """The date the bank advice is filed under, read off its own name."""
    m = DATE_IN_NAME.match(file_name)
    if not m:
        return ''
    mm, dd, yy = m.groups()
    return f'20{yy}-{mm}-{dd}'


def main():
    wb = openpyxl.load_workbook(SRC, data_only=True)
    ws = wb['Procurement Monitoring']

    # RFP number -> {url: file name}. A dict rather than a list because the same
    # advice is hyperlinked on every line of a multi-line request.
    proof = defaultdict(dict)
    for row in ws.iter_rows(min_row=6):
        cells = [c.value for c in row]
        if not cells or not cells[0]:
            continue
        ref = text(cells[2])
        cell = row[29]
        if ref and cell.hyperlink and cell.hyperlink.target:
            proof[ref][cell.hyperlink.target] = text(cell.value)

    out = []
    w = out.append
    w("-- 0056 · The proof of payment was in the sheet all along")
    w("--")
    w("-- Generated by scripts/generate-proof-of-payment.py. Do not hand-edit.")
    w("--")
    w("-- Each bank advice is a hyperlink on the payment reference cell, pointing")
    w("-- at a PDF in the company SharePoint. The file name carries the date, the")
    w("-- payee, the bank and the amount, so a payment that looked like a bare")
    w("-- reference turns out to have a document behind it after all.")
    w("--")
    w("-- The amount on the advice is not used to set the amount settled: one")
    w("-- advice routinely covers several requests, and what the bank paid out")
    w("-- that day is a different question from what this request was for.")
    w("--")
    w("-- Re-runnable: every insert is guarded on the pair of the request and the")
    w("-- document URL, and the updates only fill what is empty.")
    w("")

    docs = 0
    marked = 0
    ordered = sorted(proof)

    for ref in ordered:
        for url in sorted(proof[ref], key=lambda u: proof[ref][u]):
            name = proof[ref][url]
            w("INSERT INTO erp_attachments(module_code,record_type,record_no,record_id,file_name,"
              "content_type,storage,file_url,uploaded_by)"
              f" SELECT 'FINANCE','PAYMENT_PROOF',{q(ref)},"
              f"(SELECT id FROM erp_payment_requests WHERE request_no={q(ref)}),"
              f"{q(name)},'application/pdf','LINK',{q(url)},{q(IMPORT_ACTOR)}"
              " WHERE NOT EXISTS (SELECT 1 FROM erp_attachments a WHERE a.record_type='PAYMENT_PROOF'"
              f" AND a.record_no={q(ref)} AND a.file_url={q(url)});")
            docs += 1

    w("")
    w("-- A request that carries an advice was paid, whatever the status column")
    w("-- of the sheet said. The date comes off the document rather than being")
    w("-- guessed.")
    for ref in ordered:
        if ref in PARTIAL:
            continue
        dates = sorted(filter(None, (paid_date_of(n) for n in proof[ref].values())))
        when = dates[0] if dates else ''
        # DRAFT only, and only while nobody has recorded a payment of their own.
        # A request somebody has since part paid, voided or corrected is theirs,
        # and the loader must not put it back on the next deploy.
        w("UPDATE erp_payment_requests SET status='PAID',"
          f"paid_at=COALESCE(NULLIF(paid_at,''),{q(when)}),"
          f"paid_by=COALESCE(paid_by,{q(IMPORT_ACTOR)}),updated_at=datetime('now')"
          f" WHERE request_no={q(ref)} AND status='DRAFT'"
          " AND NOT EXISTS (SELECT 1 FROM erp_payment_settlements s"
          f" WHERE s.request_no={q(ref)});")
        marked += 1

    w("")
    w("-- 0055 writes a settlement for everything standing as paid; anything the")
    w("-- statements above have just moved onto PAID needs one too.")
    w("INSERT INTO erp_payment_settlements")
    w("  (request_no,payment_request_id,amount,paid_date,payment_reference,source,recorded_by,notes,natural_key)")
    w("SELECT r.request_no, r.id, r.net_payable,")
    w("       NULLIF(COALESCE(r.paid_at,''),''), NULLIF(COALESCE(r.payment_reference,''),''),")
    w("       'REGISTER_IMPORT', COALESCE(r.paid_by,r.requestor_email),")
    w("       'Settled per the 2026 procurement register.', 'FULL:'||r.request_no")
    w("  FROM erp_payment_requests r")
    w(" WHERE r.status='PAID'")
    w("   AND NOT EXISTS (SELECT 1 FROM erp_payment_settlements s")
    w("                    WHERE s.request_no=r.request_no AND s.status<>'VOID');")

    w("")
    w("-- Point each settlement at its advice: the earliest document on the")
    w("-- request, since that is the one that proves the payment being recorded.")
    w("-- Where the sheet never gave a paid date, the document's own name does.")
    for ref in ordered:
        dates = sorted(filter(None, (paid_date_of(n) for n in proof[ref].values())))
        when = dates[0] if dates else ''
        w("UPDATE erp_payment_settlements SET"
          " proof_attachment_id=COALESCE(proof_attachment_id,(SELECT MIN(a.id) FROM erp_attachments a"
          f" WHERE a.record_type='PAYMENT_PROOF' AND a.record_no={q(ref)} AND a.active=1)),"
          " proof_reference=COALESCE(proof_reference,(SELECT a.file_name FROM erp_attachments a"
          f" WHERE a.record_type='PAYMENT_PROOF' AND a.record_no={q(ref)} AND a.active=1"
          " ORDER BY a.id LIMIT 1)),"
          f" proof_uploaded_by=COALESCE(proof_uploaded_by,{q(IMPORT_ACTOR)}),"
          " proof_uploaded_at=COALESCE(proof_uploaded_at,datetime('now')),"
          f" paid_date=COALESCE(NULLIF(paid_date,''),{q(when)})"
          f" WHERE request_no={q(ref)} AND status<>'VOID'"
          " AND source='REGISTER_IMPORT'"
          " AND proof_attachment_id IS NULL AND COALESCE(proof_reference,'')='';")

    w("")
    w("-- And the trail the RFP screen reads, so a request opened from the")
    w("-- approval chain shows the same evidence as the payments card.")
    w("INSERT INTO erp_rfp_proof_of_payment(rfp_ref,reference,paid_at,actor)")
    w("SELECT a.record_no, a.file_name,")
    w("       (SELECT MIN(s.paid_date) FROM erp_payment_settlements s")
    w("         WHERE s.request_no=a.record_no AND s.status<>'VOID'),")
    w("       a.uploaded_by")
    w("  FROM erp_attachments a")
    w(" WHERE a.record_type='PAYMENT_PROOF' AND a.active=1")
    w("   AND NOT EXISTS (SELECT 1 FROM erp_rfp_proof_of_payment p")
    w("                    WHERE p.rfp_ref=a.record_no AND p.reference=a.file_name);")
    w("")

    multi = {r: len(v) for r, v in proof.items() if len(v) > 1}
    w(f"-- {len(proof)} requests carry an advice, {docs} documents in all.")
    w(f"-- {len(multi)} of them carry more than one:")
    for r in sorted(multi):
        w(f"--   {r}: {multi[r]} documents")

    # D1 refuses a file of more than about two thousand statements, so this goes
    # out in parts the same way the register did.
    header = [l for l in out if l.startswith('--')][:13]
    body = [l for l in out if not l.startswith('--')]
    CHUNK = 400
    parts = [body[i:i + CHUNK] for i in range(0, len(body), CHUNK)] or [[]]
    written = []
    for n, part in enumerate(parts, 1):
        name = OUT.replace('.sql', f'_{n:02d}.sql')
        with open(name, 'w', encoding='utf-8') as fh:
            fh.write('\n'.join(header + [f'-- Part {n} of {len(parts)}.', ''] + part) + '\n')
        written.append(name)

    print(f'{len(proof)} requests with an advice, {docs} documents, {marked} status statements')
    for name in written:
        print('  ' + name)


if __name__ == '__main__':
    main()
