"""
Turns E88_ProcurementMonitoring_2026.xlsx into a re-runnable migration.

The sheet is kept one row per procurement line, several lines to a request for
payment, and one RFP document per request sitting in Drive. The system needs the
same shape: a payment request that somebody raised once, the lines it was made
of - because a single RFP can carry a dozen account titles and the general
ledger has to post each of them separately - and the signed document attached
to the record rather than living only in a spreadsheet column.

Status is taken from the sheet rather than assumed, and the sheet records
payment two ways. Most lines carry a paid date. The rest carry a payment
reference instead - CHECK, PDC, LIQUIDATION - because a cheque was cut or a
cash advance was liquidated and nobody went back to fill the date in. Reading
only the date column would file 78 settled requests as unpaid.

So a line counts as paid if it has a paid date or a real payment reference.
"NOT FOUND" is not a reference, it is somebody recording that they could not
find one, and it is treated as unpaid.

    python3 scripts/generate-procurement-2026.py
"""
import datetime
import re
from collections import defaultdict

import openpyxl

SRC = 'source_data/E88_ProcurementMonitoring_2026.xlsx'
OUT = 'migrations/0051_procurement_register_2026.sql'

# The register is a record of what the company committed to, not a person's
# personal queue, so it is not filed under anyone's name.
IMPORT_ACTOR = 'procurement-register@nrdev.ph'


def text(v):
    if v is None:
        return ''
    if isinstance(v, datetime.datetime):
        return v.strftime('%Y-%m-%d')
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return str(v).strip()


def num(v):
    try:
        return round(float(v or 0), 2)
    except (TypeError, ValueError):
        return 0.0


def q(v):
    """A SQL string literal, or NULL for nothing at all."""
    s = text(v)
    return 'NULL' if s == '' else "'" + s.replace("'", "''") + "'"


def drive_id(url):
    m = re.search(r'/d/([A-Za-z0-9_-]{20,})', text(url))
    return m.group(1) if m else ''


# Words that appear in the reference column but are not evidence of a payment.
NOT_A_REFERENCE = {'NOT FOUND', 'N/A', 'NA', 'NONE', 'TBA', 'TBD', 'PENDING', '-'}


def line_is_paid(row):
    if text(row[30]):
        return True
    ref = text(row[29]).upper()
    return bool(ref) and ref not in NOT_A_REFERENCE


REQUEST_TYPES = {
    'payment to vendor': 'Payment to Vendor',
    'reimbursement': 'Reimbursement',
    'cash advance': 'Cash Advance',
    'liquidation': 'Liquidation',
}


def main():
    wb = openpyxl.load_workbook(SRC, data_only=True)

    links = {}
    for row in wb['URL_Mapping'].iter_rows(min_row=1, values_only=True):
        if row and row[0]:
            links[text(row[0])] = text(row[1] if len(row) > 1 else '')

    rows = [r for r in wb['Procurement Monitoring'].iter_rows(min_row=6, values_only=True) if r and r[0]]
    by_rfp = defaultdict(list)
    for r in rows:
        ref = text(r[2])
        if ref:
            by_rfp[ref].append(r)

    out = []
    w = out.append
    w("-- 0051 · The 2026 procurement register")
    w("--")
    w("-- Generated by scripts/generate-procurement-2026.py from")
    w("-- E88_ProcurementMonitoring_2026.xlsx. Do not hand-edit: regenerate.")
    w("--")
    w("-- One payment request per RFP number, one line per procurement row, and")
    w("-- the signed RFP linked from Drive. Lines carry their own account title")
    w("-- and VAT split, because a single request routinely spans several titles")
    w("-- and the ledger has to post each of them on its own.")
    w("--")
    w("-- Re-runnable: INSERT OR IGNORE throughout, keyed on the RFP number.")
    w("")

    headers = lines_sql = attach = 0
    missing_link = []

    for ref in sorted(by_rfp):
        group = by_rfp[ref]
        first = group[0]
        dates = sorted({text(r[1]) for r in group if text(r[1])})
        paid_dates = [text(r[30]) for r in group if text(r[30])]
        all_paid = all(line_is_paid(r) for r in group)
        gross = round(sum(num(r[16]) for r in group), 2)
        vat = round(sum(num(r[20]) for r in group), 2)
        ewt = round(sum(num(r[22]) for r in group), 2)
        net = round(sum(num(r[23]) for r in group), 2)

        raw_type = text(first[7]).lower()
        req_type = REQUEST_TYPES.get(raw_type, 'Payment to Vendor')
        purpose = text(first[12]) or f'{len(group)} procurement line(s)'
        if len(group) > 1:
            purpose = f'{purpose} (+{len(group) - 1} more line(s))'
        purpose = purpose[:400]

        pay_ref = next((text(r[29]) for r in group if text(r[29])), '')
        invoice_no = next((text(r[14]) for r in group if text(r[14])), '')
        invoice_dt = next((text(r[15]) for r in group if text(r[15])), '')
        po_no = next((text(r[13]) for r in group if text(r[13])), '')
        due = next((text(r[25]) for r in group if text(r[25])), '')
        status = 'PAID' if all_paid else 'DRAFT'
        # Paid, but the sheet may not say when. Better a blank date than a
        # invented one: the reference is on the record either way.
        paid_at = max(paid_dates) if (all_paid and paid_dates) else ''

        w(f"INSERT OR IGNORE INTO erp_payment_requests(request_no,entity_id,request_date,requestor_email,"
          f"payee_name,department,cost_center,project_code,purpose,request_type,purchase_order_no,"
          f"supplier_invoice_no,invoice_date,gross_amount,vat_amount,withholding_amount,net_payable,"
          f"due_date,payment_method,status,paid_at,payment_reference) VALUES("
          f"{q(ref)},(SELECT id FROM erp_legal_entities WHERE entity_code='E88'),"
          f"{q(dates[0] if dates else '2026-01-01')},{q(IMPORT_ACTOR)},"
          f"{q(first[3])},{q(first[4])},{q(first[5])},{q(first[8])},{q(purpose)},{q(req_type)},{q(po_no)},"
          f"{q(invoice_no)},{q(invoice_dt)},{gross},{vat},{ewt},{net},"
          f"{q(due)},NULL,'{status}',{q(paid_at)},{q(pay_ref)});")
        headers += 1

        for i, r in enumerate(group, 1):
            # The budget category is the corrected accounting title and is what
            # posts to the ledger; the sheet's own Account Title is kept beside
            # it because the two disagree in places.
            w(f"INSERT OR IGNORE INTO erp_payment_request_lines(rfp_ref,line_no,proc_id,line_date,"
              f"requesting_party,account_title,source_account_title,budget_category,procurement_category,description,"
              f"project_site,cost_center,department,supplier_invoice_no,invoice_date,po_no,"
              f"gross_amount,vat_type,vat_rate,net_of_vat,input_vat,ewt_rate,ewt_amount,net_payable,"
              f"payment_reference,paid_date,remarks) VALUES("
              f"{q(ref)},{i},{q(r[0])},{q(r[1])},{q(r[6])},{q(r[10] or r[9])},{q(r[9])},{q(r[10])},{q(r[11])},"
              f"{q(text(r[12])[:400])},{q(r[8])},{q(r[5])},{q(r[4])},{q(r[14])},{q(r[15])},{q(r[13])},"
              f"{num(r[16])},{q(r[17])},{num(r[18])},{num(r[19])},{num(r[20])},{q(r[21])},{num(r[22])},"
              f"{num(r[23])},{q(r[29])},{q(r[30])},{q(text(r[33])[:300])});")
            lines_sql += 1

        url = links.get(ref, '')
        if url:
            fid = drive_id(url)
            w(f"INSERT OR IGNORE INTO erp_attachments(module_code,record_type,record_no,file_name,"
              f"content_type,storage,drive_file_id,file_url,uploaded_by) VALUES("
              f"'FINANCE','PAYMENT_REQUEST',{q(ref)},{q(ref + '.pdf')},'application/pdf','DRIVE',"
              f"{q(fid)},{q(url)},{q(IMPORT_ACTOR)});")
            attach += 1
        else:
            missing_link.append(ref)

    # The system hands out RFP numbers from a per-department sequence. Loading a
    # year of real numbers without moving those sequences on means the next
    # request the system issues collides with one already in the register, so
    # every prefix is advanced past the highest number imported under it.
    w("")
    w("-- Advance the RFP number sequences past everything imported here, so the")
    w("-- next request the system issues cannot collide with a loaded one.")
    highest = {}
    for ref in by_rfp:
        m = re.match(r'^RFP-([A-Za-z0-9]+)-0*(\d+)$', ref)
        if not m:
            continue
        key = m.group(1)
        highest[key] = max(highest.get(key, 0), int(m.group(2)))
    for key in sorted(highest):
        seq = f'PAYMENT_REQUEST_{key}'
        nxt = highest[key] + 1
        w(f"INSERT OR IGNORE INTO erp_sequences(code,next_value,prefix,width) "
          f"VALUES('{seq}',{nxt},'RFP-{key}',4);")
        w(f"UPDATE erp_sequences SET next_value={nxt} WHERE code='{seq}' AND next_value<{nxt};")

    # Point the imported attachments at their request now that the headers exist.
    w("")
    w("-- The attachment is written by RFP number because the request id is only")
    w("-- known once the header lands; this ties the two together afterwards.")
    w("UPDATE erp_attachments SET record_id=(SELECT p.id FROM erp_payment_requests p"
      " WHERE p.request_no=erp_attachments.record_no)")
    w(" WHERE record_type='PAYMENT_REQUEST' AND record_id IS NULL AND record_no IS NOT NULL;")
    w("UPDATE erp_payment_request_lines SET payment_request_id="
      "(SELECT p.id FROM erp_payment_requests p WHERE p.request_no=erp_payment_request_lines.rfp_ref)")
    w(" WHERE payment_request_id IS NULL;")
    w("")

    if missing_link:
        w("-- No Drive document was mapped for these requests. They are imported")
        w("-- without an attachment rather than left out of the register:")
        for ref in missing_link:
            w(f"--   {ref}")

    # D1 refuses a single file of this many statements ("too many terms in
    # compound SELECT"), even though SQLite itself takes it - the same reason the
    # opening data is shipped in chunks. So it is written in parts, in order.
    header_lines = [l for l in out if l.startswith('--')][:11]
    body = [l for l in out if not l.startswith('--')]
    tail = [l for l in body if l.startswith('UPDATE erp_attachments')
            or l.startswith(' WHERE record_type') or l.startswith('UPDATE erp_payment_request_lines')
            or l.startswith(' WHERE payment_request_id')]
    body = [l for l in body if l not in tail]
    CHUNK = 500
    parts = [body[i:i + CHUNK] for i in range(0, len(body), CHUNK)] or [[]]
    parts[-1] = parts[-1] + [''] + tail
    written = []
    for n, part in enumerate(parts, 1):
        name = OUT.replace('.sql', f'_{n:02d}.sql')
        with open(name, 'w', encoding='utf-8') as fh:
            fh.write('\n'.join(header_lines + [f'-- Part {n} of {len(parts)}.', ''] + part) + '\n')
        written.append(name)

    print(f'{headers} requests, {lines_sql} lines, {attach} documents linked, '
          f'{len(missing_link)} without a document')
    for name in written:
        print('  ' + name)


if __name__ == '__main__':
    main()
