"""
Puts the lease contracts where Alexis said they belong: under sales orders.

The Lease Revenue Monitoring sheet is the record of what is out with customers.
Thirty-five contracts across twenty-nine clients, a hundred and ten units, a
hundred and sixty-four batteries, and nineteen of those contracts still running
today covering a hundred and seven units.

Until now none of that was in the system, which is why the fleet reads as zero
units leased while a hundred and seven of them are standing in somebody else's
yard. A unit nobody can find in the warehouse is not missing if it is out on a
contract, and the count has no way to say so unless the contract exists.

So each contract becomes a sales order of type LEASE, carrying its client, its
batch, the term, the price per day and the units by model. Sales orders already
take an uploaded document, so the signed contract hangs on the order rather
than in a folder somebody has to remember.

    python3 scripts/generate-lease-contracts.py
"""
import datetime
import re

import openpyxl

SRC = 'source_data/E88_LeaseContracts.xlsx'
OUT = 'migrations/0061_lease_contracts.sql'
ACTOR = 'lease-register@nrdev.ph'

# Columns on SCHED, from the header at row 4.
C_CLIENT, C_ADDENDUM, C_CLIENT_CODE, C_BATCH, C_CB, C_TXN_TYPE, C_TXN_CODE = 1, 2, 3, 4, 5, 6, 7
C_PRICE_DAY, C_START, C_END, C_UNITS = 8, 9, 10, 11
C_R280, C_R280S, C_D400, C_KIT, C_BATTERY = 12, 13, 14, 15, 16


def text(v):
    if v is None:
        return ''
    if isinstance(v, datetime.datetime):
        return v.strftime('%Y-%m-%d')
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return str(v).strip()


def num(v):
    try:
        return round(float(v or 0), 2)
    except (TypeError, ValueError):
        return 0.0


def q(v):
    s = text(v)
    return 'NULL' if s == '' else "'" + s.replace("'", "''") + "'"


def code_of(name, taken):
    """A short stable partner code, unique among the ones already handed out."""
    base = re.sub(r'[^A-Z0-9]', '', text(name).upper())[:8] or 'CUST'
    code = 'CUS-' + base
    n = 2
    while code in taken:
        code = f'CUS-{base}-{n}'
        n += 1
    taken.add(code)
    return code


def main():
    wb = openpyxl.load_workbook(SRC, data_only=True)
    ws = wb['SCHED']

    rows = []
    for i, r in enumerate(ws.iter_rows(min_row=6, values_only=True), start=6):
        if not r:
            continue
        client = text(r[C_CLIENT])
        # The sheet ends in a totals block: a row headed TOTAL UNITS and then a
        # column of bare numbers. Those are not clients, and importing them
        # created thirteen contracts for customers called "3" and "14".
        #
        # A contract has a client whose name is not just a number, and either a
        # start date or units against it.
        if not client or client.upper().startswith('TOTAL'):
            continue
        if re.fullmatch(r'[\d.,]+', client):
            continue
        if not text(r[C_START]) and num(r[C_UNITS]) == 0:
            continue
        rows.append({
            'key': f'LEASE:SCHED:{i}',
            'client': text(r[C_CLIENT]),
            'addendum': text(r[C_ADDENDUM]),
            'client_code': text(r[C_CLIENT_CODE]),
            'batch': text(r[C_BATCH]),
            'cb': text(r[C_CB]),
            'txn_type': text(r[C_TXN_TYPE]) or 'LSE',
            'txn_code': text(r[C_TXN_CODE]),
            'price_day': num(r[C_PRICE_DAY]),
            'start': text(r[C_START]),
            'end': text(r[C_END]),
            'units': int(num(r[C_UNITS])),
            'r280': int(num(r[C_R280])), 'r280s': int(num(r[C_R280S])),
            'd400': int(num(r[C_D400])), 'kits': int(num(r[C_KIT])),
            'batteries': int(num(r[C_BATTERY])),
        })

    clients = {}
    taken = set()
    for r in rows:
        if r['client'] not in clients:
            clients[r['client']] = code_of(r['client'], taken)

    out = []
    w = out.append
    w("-- 0061 · The lease contracts, as sales orders")
    w("--")
    w("-- Generated by scripts/generate-lease-contracts.py. Do not hand-edit.")
    w("--")
    w("-- The Lease Revenue Monitoring sheet is the record of what is out with")
    w("-- customers, and none of it was in the system. That is why the fleet")
    w("-- reads zero leased while a hundred and seven units are standing in")
    w("-- somebody else's yard, and why a count cannot tell a missing unit from")
    w("-- a deployed one.")
    w("--")
    w("-- A contract is a sales order of type LEASE. Sales orders already take an")
    w("-- uploaded document, so the signed contract hangs on the order.")
    w("--")
    w("-- Re-runnable: keyed on the sheet row.")
    w("")

    w("/*")
    w(" * The system already models a lease contract - 0018 built it, with the")
    w(" * customer, the term, the daily rate, the unit list and a place for the")
    w(" * signed document. Nothing was ever loaded into it. So this fills the")
    w(" * table that exists rather than inventing a second one beside it.")
    w(" *")
    w(" * What that table has no room for is the batch: the sheet keys everything")
    w(" * on a client-batch code, and the SOA tab bills against it. That goes in a")
    w(" * side table, along with the model split, so the contract can be found by")
    w(" * the code Finance actually uses.")
    w(" */")
    w("CREATE TABLE IF NOT EXISTS erp_lease_contract_batches (")
    w("  lease_contract_id INTEGER PRIMARY KEY REFERENCES erp_lease_contracts(id),")
    w("  cb_code TEXT NOT NULL,            -- client + batch, the key the SOA bills on")
    w("  client_code TEXT,")
    w("  batch_code TEXT,")
    w("  addendum TEXT,")
    w("  transaction_type TEXT,            -- LSE | L2O")
    w("  transaction_code TEXT,")
    w("  units_r280 INTEGER NOT NULL DEFAULT 0,")
    w("  units_r280s INTEGER NOT NULL DEFAULT 0,")
    w("  units_d400 INTEGER NOT NULL DEFAULT 0,")
    w("  charging_kits INTEGER NOT NULL DEFAULT 0,")
    w("  batteries INTEGER NOT NULL DEFAULT 0,")
    w("  source_key TEXT UNIQUE")
    w(");")
    w("CREATE INDEX IF NOT EXISTS idx_lease_batch_cb ON erp_lease_contract_batches(cb_code);")
    w("")

    w("/*")
    w(" * Which unit is out on which contract, and when it came back.")
    w(" *")
    w(" * erp_lease_contract_units says which units a contract covers. This says")
    w(" * where a unit physically is, which is a different question and the one a")
    w(" * count asks: a serial nobody can find in the warehouse is not missing if")
    w(" * it is standing in a customer's yard.")
    w(" *")
    w(" * Returning closes the row rather than deleting it, because where a unit")
    w(" * has been is part of its history.")
    w(" */")
    w("CREATE TABLE IF NOT EXISTS erp_asset_deployments (")
    w("  id INTEGER PRIMARY KEY AUTOINCREMENT,")
    w("  serial_no TEXT NOT NULL,")
    w("  asset_id INTEGER REFERENCES erp_assets(id),")
    w("  lease_contract_id INTEGER REFERENCES erp_lease_contracts(id),")
    w("  sales_order_id INTEGER REFERENCES erp_sales_orders(id),")
    w("  cb_code TEXT,")
    w("  customer_id INTEGER REFERENCES erp_partners(id),")
    w("  customer_name TEXT,")
    w("  deployed_at TEXT NOT NULL DEFAULT (datetime('now')),")
    w("  deployed_by TEXT,")
    w("  count_sheet_id INTEGER,           -- when a count is what discovered it")
    w("  returned_at TEXT,")
    w("  returned_by TEXT,")
    w("  return_reason TEXT,")
    w("  note TEXT")
    w(");")
    w("CREATE INDEX IF NOT EXISTS idx_deploy_serial ON erp_asset_deployments(serial_no, returned_at);")
    w("CREATE INDEX IF NOT EXISTS idx_deploy_contract ON erp_asset_deployments(lease_contract_id);")
    w("-- A serial is out on one contract at a time.")
    w("CREATE UNIQUE INDEX IF NOT EXISTS ux_deploy_open ON erp_asset_deployments(serial_no)")
    w("  WHERE returned_at IS NULL;")
    w("")

    w("-- The clients on the contracts, as customers.")
    for name in sorted(clients):
        w("INSERT INTO erp_partners(partner_code,partner_type,name,active,source_system,source_key)"
          f" SELECT {q(clients[name])},'CUSTOMER',{q(name)},1,'LEASE_CONTRACTS',{q('LEASE:'+name)}"
          f" WHERE NOT EXISTS (SELECT 1 FROM erp_partners p WHERE UPPER(TRIM(p.name))={q(name.upper())}"
          "  AND p.partner_type='CUSTOMER');")

    w("")
    w("-- A sales order per contract, the contract itself, and the batch beside it.")
    for n, r in enumerate(rows, start=1):
        so = f"SO-LSE-{n:04d}"
        lease_no = f"LSE-{n:04d}"
        cb = r['cb'] or f"{r['client_code'] or r['client'][:4].upper()}-{r['batch'] or n}"
        days = 0
        months = 0
        if r['start'] and r['end']:
            try:
                d1 = datetime.date.fromisoformat(r['start'])
                d2 = datetime.date.fromisoformat(r['end'])
                days = max(0, (d2 - d1).days)
                months = round(days / 30.44)
            except ValueError:
                days = months = 0
        # What the term is worth at the daily rate: the figure the contract is
        # signed for, rather than a month of it.
        value = round(r['price_day'] * max(r['units'], 1) * days, 2)
        cust = (f"(SELECT id FROM erp_partners WHERE UPPER(TRIM(name))={q(r['client'].upper())}"
                "  AND partner_type='CUSTOMER' ORDER BY id LIMIT 1)")
        w("INSERT INTO erp_sales_orders(sales_order_no,transaction_type,customer_id,order_date,"
          "contract_start,contract_end,status,gross_amount,source_system,source_key,created_by)"
          f" SELECT {q(so)},'LEASE',{cust},"
          f"{q(r['start'])},{q(r['start'])},{q(r['end'])},'CONFIRMED',{value},"
          f"'LEASE_CONTRACTS',{q(r['key'])},{q(ACTOR)}"
          f" WHERE NOT EXISTS (SELECT 1 FROM erp_sales_orders s WHERE s.source_key={q(r['key'])})"
          f"   AND {cust} IS NOT NULL;")
        descr = (f"{r['units']} unit(s): {r['r280']} R280, {r['r280s']} R280S, {r['d400']} D400"
                 f" · {r['batteries']} batteries, {r['kits']} charging kit(s)")
        w("INSERT INTO erp_lease_contracts(lease_no,sales_order_id,customer_id,business_channel,"
          "client_name,leased_units_description,contract_term_months,effective_date,end_of_term,"
          "daily_rate_vat_ex,unit_count,status,created_by)"
          f" SELECT {q(lease_no)},"
          f"(SELECT id FROM erp_sales_orders WHERE source_key={q(r['key'])}),{cust},'B2B',"
          f"{q(r['client'])},{q(descr)},{months},{q(r['start'])},{q(r['end'])},"
          f"{r['price_day']},{r['units']},"
          f"CASE WHEN {q(r['end'])} >= date('now') THEN 'ACTIVE' ELSE 'ENDED' END,{q(ACTOR)}"
          f" WHERE NOT EXISTS (SELECT 1 FROM erp_lease_contracts c WHERE c.lease_no={q(lease_no)});")
        w("INSERT INTO erp_lease_contract_batches(lease_contract_id,cb_code,client_code,batch_code,"
          "addendum,transaction_type,transaction_code,units_r280,units_r280s,units_d400,"
          "charging_kits,batteries,source_key)"
          f" SELECT (SELECT id FROM erp_lease_contracts WHERE lease_no={q(lease_no)}),"
          f"{q(cb)},{q(r['client_code'])},{q(r['batch'])},{q(r['addendum'])},{q(r['txn_type'])},"
          f"{q(r['txn_code'])},{r['r280']},{r['r280s']},{r['d400']},{r['kits']},{r['batteries']},"
          f"{q(r['key'])}"
          f" WHERE NOT EXISTS (SELECT 1 FROM erp_lease_contract_batches b WHERE b.source_key={q(r['key'])})"
          f"   AND EXISTS (SELECT 1 FROM erp_lease_contracts c WHERE c.lease_no={q(lease_no)});")

    live = [r for r in rows if r['end'] >= '2026-08-08']
    w("")
    w(f"-- {len(rows)} contracts, {len(clients)} clients, "
      f"{sum(r['units'] for r in rows)} units, {sum(r['batteries'] for r in rows)} batteries.")
    w(f"-- {len(live)} still running, covering {sum(r['units'] for r in live)} units.")

    header = [l for l in out if l.startswith('--')][:12]
    body = [l for l in out if not l.startswith('--')]
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(header + [''] + body) + '\n')

    print(f'{len(rows)} contracts, {len(clients)} clients, '
          f'{sum(r["units"] for r in rows)} units, {sum(r["batteries"] for r in rows)} batteries')
    print(f'{len(live)} still running, {sum(r["units"] for r in live)} units')
    print('  ' + OUT)


if __name__ == '__main__':
    main()
